import type { Chapter } from "../types";

// NCERT Class 7 Science — redesigned around a "Mystery Lab" detective frame:
// discover-then-name, with bespoke interactives at each discovery point.
// Tracked question ids (abs-bq-*, abs-quiz-*) are stable — never reuse them
// for different questions.
export const acidsBasesSaltsChapter: Chapter = {
  slug: "acids-bases-salts",
  title: "Acids, Bases and Salts",
  subject: "Science",
  emoji: "🧪",
  color: "#d85a30",
  description: "Become a lab detective: identify mystery liquids, tame an acid, and crack the three-bottle case.",
  scenes: [
    {
      type: "concept",
      id: "hook",
      eyebrow: "🕵️ Your Mission",
      title: "Welcome to the Mystery Lab",
      body: "On the bench sits a tray of unlabeled liquids from an ordinary kitchen — and your job, detective, is to identify every single one by the end of this chapter. You'll earn new tools as you go. First clue: your tongue already knows something about chemistry…",
    },
    {
      type: "concept",
      id: "taste-clue",
      eyebrow: "👅 Clue #1: Taste",
      title: "Sour, sweet, salty, bitter",
      body: "Tap each food. Notice the pattern: some things are sharply sour (khatta), some are bitter (kadwa). That's not an accident — it's chemistry talking. But real scientists NEVER taste unknown chemicals. We need a safer tool…",
      cards: [
        { icon: "🍋", front: "Lemon", back: "Sour — it contains citric acid." },
        { icon: "🥣", front: "Curd", back: "Sour — it contains lactic acid." },
        { icon: "🥬", front: "Karela", back: "Bitter — a property shared by bases." },
        { icon: "💧", front: "Water", back: "No sour, no bitter — some things are neither!" },
      ],
    },
    { type: "custom", id: "indicator-lab", component: "indicator-lab" },
    {
      type: "concept",
      id: "indicator-tools",
      eyebrow: "🎨 Your New Tools",
      title: "Meet the indicators",
      body: "Substances that change colour to reveal an acid or base are called indicators. The ones you just used come in two families — tap the cards.",
      cards: [
        { icon: "🌿", front: "Natural", back: "From plants: litmus (from lichen), turmeric (haldi), China rose (gudhal), red cabbage juice." },
        { icon: "🏭", front: "Synthetic", back: "Man-made in labs: phenolphthalein and methyl orange." },
        { icon: "🧻", front: "Litmus", back: "Purple in neutral water; made into blue and red strips so colour changes are easy to spot." },
      ],
    },
    {
      type: "concept",
      id: "acid-properties",
      eyebrow: "🧪 Case File: ACIDS",
      title: "What you now know about acids",
      body: "Acids are sour, turn blue litmus red, and are corrosive. Mineral acids like sulphuric and hydrochloric acid are strong; organic acids are weak. Acids dissolve in water — and they react in three famous ways. Tap each card.",
      cards: [
        { icon: "⚙️", front: "Acid + Metal", back: "→ Salt + Hydrogen gas" },
        { icon: "🫧", front: "Acid + Carbonate", back: "→ Salt + Carbon dioxide gas" },
        { icon: "⚖️", front: "Acid + Base", back: "→ Salt + Water (you'll experiment with this soon!)" },
      ],
    },
    {
      type: "concept",
      id: "acid-types",
      eyebrow: "🗂️ Classification",
      title: "Where do acids come from?",
      body: "Two sources, two families. Tap each card.",
      cards: [
        { icon: "🌿", front: "Organic Acid", back: "Occurs naturally in plants and animals — citric acid in lemons, lactic acid in curd. All organic acids are weak." },
        { icon: "⛏️", front: "Mineral Acid", back: "Made from earth minerals in a lab — HCl, H₂SO₄, HNO₃. Also called laboratory acids. Almost all are strong." },
      ],
    },
    {
      type: "match",
      id: "organic-acid-match",
      eyebrow: "🎮 Evidence Board",
      title: "Match the organic acid to its source",
      prompt: "Tap an acid, then tap where it's found in nature.",
      pairs: [
        { left: "Acetic acid", right: "Vinegar (sirka)" },
        { left: "Formic acid", right: "Ant's sting" },
        { left: "Citric acid", right: "Lemons & oranges" },
        { left: "Lactic acid", right: "Curd / sour milk" },
        { left: "Tartaric acid", right: "Tamarind (imli)" },
        { left: "Ascorbic acid (Vit C)", right: "Amla" },
        { left: "Oxalic acid", right: "Spinach (palak)" },
      ],
    },
    {
      type: "concept",
      id: "mineral-acids",
      eyebrow: "⛏️ The Big Three",
      title: "Mineral acids: handle with care",
      body: "Made in factories, used everywhere. Fun fact: aqua regia — 'royal water', a 1:3 mix of nitric and hydrochloric acid — is so powerful it dissolves gold and platinum. Tap each acid.",
      cards: [
        { icon: "🧪", front: "HCl", back: "Hydrochloric acid — lab experiments, disinfectants, descaling boilers, making glue. Your stomach makes it too!" },
        { icon: "💥", front: "HNO₃", back: "Nitric acid — fertilisers, cleaning gold & silver jewellery, explosives like TNT." },
        { icon: "🔋", front: "H₂SO₄", back: "Sulphuric acid — car batteries, paints, dyes, detergents, fertilisers." },
      ],
    },
    {
      type: "sort",
      id: "strong-weak-sort",
      eyebrow: "🗂️ Sort the Evidence",
      title: "Strong acid or weak acid?",
      prompt: "Strong acids are dangerous even when dilute; weak (organic) acids are safe enough to eat! Sort them.",
      buckets: ["Strong Acid ⚠️", "Weak Acid 🍋"],
      items: [
        { label: "HCl", bucket: 0 },
        { label: "H₂SO₄", bucket: 0 },
        { label: "HNO₃", bucket: 0 },
        { label: "Acetic acid", bucket: 1 },
        { label: "Citric acid", bucket: 1 },
        { label: "Carbonic acid (in fizzy drinks!)", bucket: 1 },
      ],
    },
    {
      type: "book-question",
      id: "bq-1",
      questionId: "abs-bq-1",
      eyebrow: "📖 Practice",
      prompt: "Which of the following contains lactic acid?",
      options: [
        { id: "a", label: "Ant's sting" },
        { id: "b", label: "Unripe grapes" },
        { id: "c", label: "Lemons" },
        { id: "d", label: "Sour milk" },
      ],
      correct: "d",
      explain: "Lactic acid is present in curd and in sour milk.",
    },
    {
      type: "sort",
      id: "acid-rain-sort",
      eyebrow: "🌧️ Case File: Acid Rain",
      title: "Acid rain: cause or damage?",
      prompt: "Pollutant gases dissolve in raindrops and the rain itself turns acidic. Sort each item: is it a CAUSE of acid rain, or DAMAGE done by it?",
      buckets: ["Cause ☁️", "Damage 💔"],
      items: [
        { label: "SO₂ released into air", bucket: 0 },
        { label: "Fish die in lakes", bucket: 1 },
        { label: "NO₂ from vehicles", bucket: 0 },
        { label: "Monuments corrode", bucket: 1 },
        { label: "CO₂ dissolving in raindrops", bucket: 0 },
        { label: "Crops and leaves damaged", bucket: 1 },
        { label: "Steel bridges rust away", bucket: 1 },
      ],
    },
    {
      type: "concept",
      id: "bases-intro",
      eyebrow: "🧼 Case File: BASES",
      title: "The chemical opposites of acids",
      body: "Remember the liquids that turned red litmus blue? Those are bases — bitter (kadwa) in taste and soapy-slippery to touch (rub dilute sodium hydroxide between your fingers in a real lab and you'll feel it). A base that dissolves in water is called an alkali. Some are strong (NaOH, KOH), some weak (calcium hydroxide, ammonium hydroxide).",
    },
    {
      type: "match",
      id: "bases-match",
      eyebrow: "🎮 Evidence Board",
      title: "Match the base to its everyday name",
      prompt: "Tap a base, then tap the name you'd hear at home or in a shop.",
      pairs: [
        { left: "NaOH", right: "Caustic soda" },
        { left: "Ca(OH)₂", right: "Slaked lime" },
        { left: "Mg(OH)₂", right: "Milk of magnesia" },
        { left: "Na₂CO₃", right: "Washing soda" },
        { left: "NaHCO₃", right: "Baking soda" },
      ],
    },
    {
      type: "concept",
      id: "bases-uses",
      eyebrow: "🧼 Bases at Work",
      title: "Where bases earn their living",
      body: "Tap each card to see these bases in action.",
      cards: [
        { icon: "🧼", front: "Caustic soda (NaOH)", back: "Makes soap, paper and medicine; unblocks drains." },
        { icon: "🏠", front: "Slaked lime Ca(OH)₂", back: "Whitewashing, bleaching powder, neutralising acidic soil, treating wastewater." },
        { icon: "💊", front: "Milk of magnesia", back: "Antacid for indigestion; also a laxative." },
        { icon: "🧺", front: "Washing soda Na₂CO₃", back: "Makes glass, soap and borax; softens laundry water." },
        { icon: "🐜", front: "Baking soda NaHCO₃", back: "Treats ant stings; neutralises acids; in your cake!" },
        { icon: "🖋️", front: "Ammonium hydroxide", back: "Makes fertilisers; removes ink stains." },
      ],
    },
    {
      type: "book-question",
      id: "bq-2",
      questionId: "abs-bq-2",
      eyebrow: "📖 Practice",
      prompt: "A yellow turmeric curry stain on a white shirt turns red when soap solution is scrubbed on it. This shows the soap solution is…",
      options: [
        { id: "a", label: "Basic" },
        { id: "b", label: "Acidic" },
        { id: "c", label: "Neutral" },
        { id: "d", label: "Sour" },
      ],
      correct: "a",
      explain: "Turmeric turns reddish-brown in a base — you saw it yourself in the Indicator Lab!",
    },
    {
      type: "match",
      id: "indicator-color-match",
      eyebrow: "🎮 Memory Check",
      title: "What colour in a BASE?",
      prompt: "You tested these in the lab. Match each indicator to the colour it shows in a basic solution.",
      pairs: [
        { left: "Red litmus", right: "Blue" },
        { left: "Phenolphthalein", right: "Pink" },
        { left: "China rose", right: "Green" },
        { left: "Turmeric", right: "Reddish-brown" },
        { left: "Methyl orange", right: "Yellow" },
      ],
    },
    { type: "custom", id: "ph-slider", component: "ph-slider" },
    {
      type: "book-question",
      id: "bq-3",
      questionId: "abs-bq-3",
      eyebrow: "📖 Practice",
      prompt: "A solution with a pH value of more than 7 is said to be…",
      options: [
        { id: "a", label: "Acidic" },
        { id: "b", label: "Neutral" },
        { id: "c", label: "Basic" },
        { id: "d", label: "None of these" },
      ],
      correct: "c",
      explain: "Above 7 = basic, exactly 7 = neutral, below 7 = acidic — just like your slider.",
    },
    { type: "custom", id: "neutralisation-mixer", component: "neutralisation-mixer" },
    {
      type: "custom",
      id: "mission-ant",
      component: "rescue-mission",
      props: {
        emoji: "🐜",
        title: "The ant attack",
        situation: "An ant has stung Ravi during lunch break! Its sting injected formic acid into his skin, and it burns badly.",
        question: "What should you rub on the sting?",
        choices: [
          { id: "a", label: "Lemon juice 🍋", outcome: "It burns even MORE! Lemon juice is citric acid — you just added acid to acid." },
          { id: "b", label: "Baking soda paste 🧁", correct: true, outcome: "Relief! The burning fades away." },
          { id: "c", label: "Plain salt water 🧂", outcome: "It cleans the skin, but the burning continues — salt water is neutral, it can't cancel an acid." },
        ],
        explain: "Baking soda is a mild BASE — it neutralises the formic acid. Calamine lotion (zinc carbonate) works the same way.",
      },
    },
    {
      type: "custom",
      id: "mission-stomach",
      component: "rescue-mission",
      props: {
        emoji: "🫃",
        title: "Uncle's stomach trouble",
        situation: "Uncle overate at the wedding feast. His stomach is producing too much hydrochloric acid, causing pain and burning — indigestion!",
        question: "What will actually help him?",
        choices: [
          { id: "a", label: "A glass of lemon water 🍋", outcome: "Worse! More acid in an already-acidic stomach." },
          { id: "b", label: "Spicy pickle 🥒", outcome: "Ouch — pickle contains vinegar (acetic acid). The burning grows." },
          { id: "c", label: "Milk of magnesia 💊", correct: true, outcome: "Within minutes, Uncle feels better." },
        ],
        explain: "Milk of magnesia is an ANTACID — a mild base that neutralises the excess stomach acid.",
      },
    },
    {
      type: "custom",
      id: "mission-soil",
      component: "rescue-mission",
      props: {
        emoji: "🌾",
        title: "The farmer's failing field",
        situation: "Years of acid rain and chemical fertilisers have made Kisan Lal's soil acidic. His wheat seedlings are wilting.",
        question: "What should he mix into the soil?",
        choices: [
          { id: "a", label: "More chemical fertiliser 🧴", outcome: "The crop gets worse — excess fertiliser is part of what made the soil acidic!" },
          { id: "b", label: "Slaked lime 🏠", correct: true, outcome: "Next season, the field is green again." },
          { id: "c", label: "Vinegar spray 🫙", outcome: "Disaster — vinegar is an acid. The soil becomes even more acidic." },
        ],
        explain: "Slaked lime (or quick lime) is a base that neutralises acidic soil. If soil ever turns too BASIC, farmers add manure — decaying organic matter releases acids.",
      },
    },
    {
      type: "custom",
      id: "mission-factory",
      component: "rescue-mission",
      props: {
        emoji: "🏭",
        title: "The factory and the river",
        situation: "A factory's waste is acidic, and it flows straight into the river where fish live. The fish are in danger!",
        question: "What should the factory do before releasing the waste?",
        choices: [
          { id: "a", label: "Dump it at night so nobody sees 🌙", outcome: "The fish die either way — and that's illegal. Chemistry doesn't sleep!" },
          { id: "b", label: "Just add lots of extra water 💧", outcome: "Diluted acid is still acid — the river slowly turns acidic and aquatic life suffers." },
          { id: "c", label: "Treat it with slaked lime first 🏠", correct: true, outcome: "The waste is neutralised — the river and its fish stay safe." },
        ],
        explain: "Acidic industrial waste is neutralised with bases like slaked lime before disposal. Basic waste gets treated with acids — neutralisation works both ways.",
      },
    },
    {
      type: "book-question",
      id: "bq-4",
      questionId: "abs-bq-4",
      eyebrow: "📖 Practice",
      prompt: "Which type of medicine is used for treating indigestion caused by overeating?",
      options: [
        { id: "a", label: "Antibiotic" },
        { id: "b", label: "Analgesic" },
        { id: "c", label: "Antacid" },
        { id: "d", label: "Antiseptic" },
      ],
      correct: "c",
      explain: "You just rescued Uncle with one — antacids are mild bases that neutralise excess stomach acid.",
    },
    {
      type: "concept",
      id: "salts-intro",
      eyebrow: "🧂 Case File: SALTS",
      title: "What's left when acid meets base?",
      body: "When an acid and a base destroy each other in the right amounts, the new substance left behind is a salt. But 'salt' doesn't just mean table salt — and salts aren't always neutral! Tap the cards. (Two properties to remember: salts dissolve in water, and they conduct electricity.)",
      cards: [
        { icon: "🧂", front: "Neutral salt", back: "NaCl, NaNO₃, K₂SO₄, KCl — no acidic or basic behaviour." },
        { icon: "🧪", front: "Acidic salt", back: "NaHCO₃, NaHSO₄ — gives an acidic solution in water." },
        { icon: "🪨", front: "Basic salt", back: "CaCO₃, Na₂CO₃, LiF — gives a basic solution in water." },
      ],
    },
    {
      type: "match",
      id: "salts-match",
      eyebrow: "🎮 Evidence Board",
      title: "Match the salt to its type",
      prompt: "Tap a salt, then tap the type it belongs to.",
      pairs: [
        { left: "NaCl", right: "Neutral salt" },
        { left: "K₂SO₄", right: "Neutral salt" },
        { left: "CaCO₃", right: "Basic salt" },
        { left: "NaHCO₃", right: "Acidic salt" },
      ],
    },
    { type: "custom", id: "salt-name-factory", component: "salt-name-factory" },
    {
      type: "concept",
      id: "salt-uses",
      eyebrow: "🧂 Salts at Work",
      title: "Two famous salts",
      body: "Tap the cards to see how much everyday life runs on salts.",
      cards: [
        { icon: "🧂", front: "Sodium chloride", back: "Flavours food, softens hard water, extinguishes fires, and helps make fertilisers, medicine, shampoo and toothpaste." },
        { icon: "🔋", front: "Zinc chloride", back: "Keeps water pure, speeds up plant growth, and powers cell batteries." },
      ],
    },
    {
      type: "vocab",
      id: "keywords",
      eyebrow: "🔤 Detective's Glossary",
      title: "Words to know",
      words: [
        { word: "Indicator", meaning: "A substance that changes colour when it meets an acid or a base." },
        { word: "Acidic substance", meaning: "A substance with a pH below 7." },
        { word: "Basic substance", meaning: "A substance with a pH above 7." },
        { word: "Alkali", meaning: "A base that dissolves in water." },
        { word: "Universal indicator", meaning: "A mixture of indicators showing a different colour for every pH value." },
        { word: "Neutralisation", meaning: "Acid + Base → Salt + Water + heat: they cancel each other's effect." },
        { word: "Natural indicator", meaning: "An indicator from a natural source, like litmus (from lichen) or turmeric." },
        { word: "Synthetic indicator", meaning: "A man-made indicator, like phenolphthalein or methyl orange." },
      ],
    },
    {
      type: "book-question",
      id: "bq-5",
      questionId: "abs-bq-5",
      eyebrow: "📖 Assertion & Reason",
      prompt: "Assertion (A): The reaction between an acid and a base is known as the neutralisation reaction.\nReason (R): The neutralisation reaction forms salt and water as a product.",
      options: [
        { id: "a", label: "Both A and R are true, and R correctly explains A" },
        { id: "b", label: "Both A and R are true, but R does not explain A" },
        { id: "c", label: "A is true, but R is false" },
        { id: "d", label: "A is false, but R is true" },
      ],
      correct: "a",
      explain: "Neutralisation is defined as acid + base forming salt and water — R is exactly why A is true.",
    },
    { type: "custom", id: "three-bottles", component: "three-bottles" },
    {
      type: "quiz",
      id: "boss-quiz",
      eyebrow: "🏆 Boss Quiz",
      title: "Prove you've mastered acids, bases and salts",
      questions: [
        {
          questionId: "abs-quiz-1",
          prompt: "The reaction between an acid and a base gives…",
          options: [
            { id: "a", label: "Only salt" },
            { id: "b", label: "Only water" },
            { id: "c", label: "Only hydrogen" },
            { id: "d", label: "Both salt and water" },
          ],
          correct: "d",
          explain: "Acid + Base → Salt + Water — you made it happen in the beaker.",
        },
        {
          questionId: "abs-quiz-2",
          prompt: "Which indicator turns pink when a few drops of sodium hydroxide solution are added?",
          options: [
            { id: "a", label: "Blue litmus" },
            { id: "b", label: "Phenolphthalein" },
            { id: "c", label: "Turmeric paper" },
            { id: "d", label: "China rose indicator" },
          ],
          correct: "b",
          explain: "Phenolphthalein: colourless in acid, PINK in base — as you saw in the Indicator Lab.",
        },
        {
          questionId: "abs-quiz-3",
          prompt: "The reaction between an acid and a base to form salt and water is called…",
          options: [
            { id: "a", label: "Carbonation" },
            { id: "b", label: "Hydrogenation" },
            { id: "c", label: "Neutralisation" },
            { id: "d", label: "Titration" },
          ],
          correct: "c",
        },
        {
          questionId: "abs-quiz-4",
          prompt: "What is the common name of sodium chloride?",
          options: [
            { id: "a", label: "Baking powder" },
            { id: "b", label: "Milk of magnesia" },
            { id: "c", label: "Common salt" },
            { id: "d", label: "Methyl orange" },
          ],
          correct: "c",
        },
        {
          questionId: "abs-quiz-5",
          prompt: "Ammonium hydroxide is used at home to remove…",
          options: [
            { id: "a", label: "Rust stains" },
            { id: "b", label: "Ink stains" },
            { id: "c", label: "Oil stains" },
            { id: "d", label: "Paint stains" },
          ],
          correct: "b",
        },
        {
          questionId: "abs-quiz-6",
          prompt: "A base that is soluble in water is called a/an…",
          options: [
            { id: "a", label: "Acid" },
            { id: "b", label: "Alkali" },
            { id: "c", label: "Salt" },
            { id: "d", label: "Indicator" },
          ],
          correct: "b",
        },
        {
          questionId: "abs-quiz-7",
          prompt: "What causes the sharp pain from an ant's sting?",
          options: [
            { id: "a", label: "Acetic acid" },
            { id: "b", label: "Citric acid" },
            { id: "c", label: "Formic acid" },
            { id: "d", label: "Oxalic acid" },
          ],
          correct: "c",
          explain: "Formic acid — that's why you rescued Ravi with baking soda.",
        },
      ],
    },
    {
      type: "concept",
      id: "done",
      eyebrow: "🎉 Case Closed",
      title: "Detective, you've earned your badge",
      body: "You identified mystery liquids with indicators, explored the pH scale, neutralised an acid with your own hands, rescued four people with chemistry, named salts like a factory, and cracked the three-bottle case. Every liquid on that tray now has a label — mission complete!",
    },
  ],
};
