import type { Chapter } from "../types";

// Ported from the NCERT Class 7 Science chapter text the teacher supplied.
// Stable question ids (abs-bq-*, abs-quiz-*) so attempts stay analysable if
// wording is tweaked later.
export const acidsBasesSaltsChapter: Chapter = {
  slug: "acids-bases-salts",
  title: "Acids, Bases and Salts",
  subject: "Science",
  emoji: "🧪",
  color: "#d85a30",
  description: "Sour, bitter or neither? Learn what makes something an acid, a base or a salt.",
  scenes: [
    {
      type: "concept",
      id: "hook",
      eyebrow: "🍋 Let's Begin",
      title: "How does it taste?",
      body: "Lemon is sour, sugar is sweet, salt is salty, and karela (bitter gourd) is bitter. That sour and bitter taste is a big clue about the chemistry hiding inside our food — let's find out why.",
      cards: [
        { icon: "🍋", front: "Lemon", back: "Sour — because it contains citric acid." },
        { icon: "🥣", front: "Curd", back: "Sour — because it contains lactic acid." },
        { icon: "🥬", front: "Karela", back: "Bitter — a property shared by bases." },
      ],
    },
    {
      type: "concept",
      id: "intro",
      eyebrow: "📖 Concept",
      title: "Acids, bases and salts are everywhere",
      body: "Acids and bases can occur naturally or be made in a lab. Acids taste sour; bases taste bitter. Salts can be natural or man-made. Some substances — like water, glucose and cane sugar — are neither acidic nor basic. We call them neutral.",
    },
    {
      type: "concept",
      id: "acid-properties",
      eyebrow: "🧪 Properties",
      title: "What makes something an acid?",
      body: "Acids taste sour, turn blue litmus red, and are corrosive. They can be strong (mineral acids like HCl) or weak (organic acids). Acids are soluble in water and take part in three key reactions — tap each card.",
      cards: [
        { icon: "⚙️", front: "Acid + Metal", back: "→ Salt + Hydrogen gas" },
        { icon: "🫧", front: "Acid + Carbonate", back: "→ Salt + Carbon dioxide gas" },
        { icon: "⚖️", front: "Acid + Base", back: "→ Salt + Water (neutralisation)" },
      ],
    },
    {
      type: "concept",
      id: "acid-types",
      eyebrow: "🗂️ Classification",
      title: "Two types of acids",
      body: "Acids are grouped by where they come from. Tap each card to see the difference.",
      cards: [
        { icon: "🌿", front: "Organic Acid", back: "Occurs naturally in plants and animals — e.g. citric acid in lemons, lactic acid in curd." },
        { icon: "⛏️", front: "Mineral Acid", back: "Made from earth minerals in a lab — e.g. HCl, H₂SO₄, HNO₃. Also called laboratory acids." },
      ],
    },
    {
      type: "match",
      id: "organic-acid-match",
      eyebrow: "🎮 Mini-game",
      title: "Match the organic acid to its source",
      prompt: "Tap an acid, then tap where it's found.",
      pairs: [
        { left: "Acetic acid", right: "Vinegar" },
        { left: "Formic acid", right: "Ant's sting" },
        { left: "Citric acid", right: "Citrus fruits" },
        { left: "Lactic acid", right: "Curd / sour milk" },
        { left: "Tartaric acid", right: "Tamarind" },
      ],
    },
    {
      type: "concept",
      id: "mineral-acids",
      eyebrow: "⛏️ Mineral Acids",
      title: "The big three lab acids",
      body: "These strong acids are made in factories and used across industry. Aqua regia — a 1:3 mix of nitric and hydrochloric acid — is nicknamed 'royal water' because it can dissolve gold and platinum.",
      cards: [
        { icon: "🧪", front: "HCl", back: "Hydrochloric acid — used in labs, disinfectants, and to make glue." },
        { icon: "🧪", front: "HNO₃", back: "Nitric acid — used to make fertilisers and explosives like TNT." },
        { icon: "🧪", front: "H₂SO₄", back: "Sulphuric acid — used in car batteries, dyes and detergents." },
      ],
    },
    {
      type: "sort",
      id: "strong-weak-sort",
      eyebrow: "🗂️ Sort it",
      title: "Strong acid or weak acid?",
      prompt: "Tap each acid, then tap the bucket it belongs to.",
      buckets: ["Strong Acid", "Weak Acid"],
      items: [
        { label: "HCl", bucket: 0 },
        { label: "H₂SO₄", bucket: 0 },
        { label: "HNO₃", bucket: 0 },
        { label: "Acetic acid", bucket: 1 },
        { label: "Citric acid", bucket: 1 },
        { label: "Carbonic acid", bucket: 1 },
      ],
    },
    {
      type: "book-question",
      id: "bq-1",
      questionId: "abs-bq-1",
      eyebrow: "📖 Practice",
      prompt: "Which of the following contains lactic acid?",
      options: [
        { id: "a", label: "Ant's sting" },
        { id: "b", label: "Unripe grapes" },
        { id: "c", label: "Lemons" },
        { id: "d", label: "Sour milk" },
      ],
      correct: "d",
      explain: "Lactic acid is present in curd and in sour milk.",
    },
    {
      type: "concept",
      id: "acid-rain",
      eyebrow: "🌧️ Acid Rain",
      title: "When the sky turns acidic",
      body: "Pollutant gases — sulphur dioxide, nitrogen dioxide and carbon dioxide — dissolve in raindrops and make the rain acidic. Acid rain kills fish in lakes, damages tree leaves and crops, corrodes steel bridges, and erodes stone buildings and monuments.",
    },
    {
      type: "concept",
      id: "bases-intro",
      eyebrow: "🧼 Concept",
      title: "What makes something a base?",
      body: "Bases taste bitter and feel soapy and slippery — try rubbing a little dilute sodium hydroxide between your fingers (in a real lab, carefully!). Bases turn red litmus blue and react with acids to form salt and water. A base that dissolves in water is called an alkali.",
    },
    {
      type: "match",
      id: "bases-match",
      eyebrow: "🎮 Mini-game",
      title: "Match the base to its common name",
      prompt: "Tap a base, then tap its everyday name.",
      pairs: [
        { left: "NaOH", right: "Caustic soda" },
        { left: "Ca(OH)₂", right: "Slaked lime" },
        { left: "Mg(OH)₂", right: "Milk of magnesia" },
        { left: "Na₂CO₃", right: "Washing soda" },
        { left: "NaHCO₃", right: "Baking soda" },
      ],
    },
    {
      type: "concept",
      id: "bases-uses",
      eyebrow: "🧼 Everyday Uses",
      title: "Bases at work",
      body: "Tap each card to see where you'd find these bases in real life.",
      cards: [
        { icon: "🧼", front: "Caustic soda", back: "Used to manufacture soap, paper and to unblock drains." },
        { icon: "🏠", front: "Slaked lime", back: "Used for whitewashing and to make bleaching powder." },
        { icon: "💊", front: "Milk of magnesia", back: "Used as an antacid and a laxative." },
        { icon: "🐜", front: "Baking soda", back: "Used to treat ant's stings and neutralise acids." },
      ],
    },
    {
      type: "book-question",
      id: "bq-2",
      questionId: "abs-bq-2",
      eyebrow: "📖 Practice",
      prompt: "A yellow turmeric curry stain on a white shirt turns red when soap solution is scrubbed on it. This shows the soap solution is…",
      options: [
        { id: "a", label: "Basic" },
        { id: "b", label: "Acidic" },
        { id: "c", label: "Neutral" },
        { id: "d", label: "Sour" },
      ],
      correct: "a",
      explain: "Turmeric paper turns red in a basic solution — that's exactly what soap is.",
    },
    {
      type: "concept",
      id: "indicators-intro",
      eyebrow: "🎨 Indicators",
      title: "How do we know it's an acid or a base?",
      body: "Indicators change colour when they touch an acid or a base. Natural indicators come from plants — litmus, turmeric, China rose. Synthetic (man-made) indicators include phenolphthalein and methyl orange.",
    },
    {
      type: "match",
      id: "indicator-color-match",
      eyebrow: "🎮 Mini-game",
      title: "Match the indicator to its colour in a base",
      prompt: "Tap an indicator, then tap the colour it turns in a basic solution.",
      pairs: [
        { left: "Litmus paper", right: "Blue" },
        { left: "Phenolphthalein", right: "Pink" },
        { left: "China rose indicator", right: "Green" },
        { left: "Turmeric", right: "Reddish-brown" },
      ],
    },
    {
      type: "concept",
      id: "ph-scale",
      eyebrow: "📏 pH Scale",
      title: "The universal indicator and pH",
      body: "A universal indicator is a mixture of indicators that shows a different colour for every pH value. The pH scale runs from 1 to 14: below 7 is acidic, exactly 7 is neutral, and above 7 is basic.",
    },
    {
      type: "book-question",
      id: "bq-3",
      questionId: "abs-bq-3",
      eyebrow: "📖 Practice",
      prompt: "A solution with a pH value of more than 7 is said to be…",
      options: [
        { id: "a", label: "Acidic" },
        { id: "b", label: "Neutral" },
        { id: "c", label: "Basic" },
        { id: "d", label: "None of these" },
      ],
      correct: "c",
      explain: "pH above 7 = basic. pH exactly 7 = neutral. pH below 7 = acidic.",
    },
    {
      type: "concept",
      id: "neutralisation",
      eyebrow: "⚖️ Big Idea",
      title: "Acid + Base = Salt + Water + heat",
      body: "When an acid reacts with a base, they cancel each other's effect — this is called neutralisation. Salt and water form, and some heat is released.",
    },
    {
      type: "match",
      id: "neutralisation-uses-match",
      eyebrow: "🎮 Mini-game",
      title: "Match the problem to its remedy",
      prompt: "Tap a problem, then tap what neutralises it.",
      pairs: [
        { left: "Indigestion", right: "Antacid (milk of magnesia)" },
        { left: "Ant's sting", right: "Baking soda" },
        { left: "Acidic soil", right: "Slaked lime" },
        { left: "Tooth decay", right: "Basic toothpaste" },
      ],
    },
    {
      type: "book-question",
      id: "bq-4",
      questionId: "abs-bq-4",
      eyebrow: "📖 Practice",
      prompt: "Which type of medicine is used for treating indigestion caused by overeating?",
      options: [
        { id: "a", label: "Antibiotic" },
        { id: "b", label: "Analgesic" },
        { id: "c", label: "Antacid" },
        { id: "d", label: "Antiseptic" },
      ],
      correct: "c",
      explain: "Antacids are mild bases that neutralise excess acid in the stomach.",
    },
    {
      type: "concept",
      id: "salts-intro",
      eyebrow: "🧂 Salts",
      title: "What is a salt?",
      body: "When an acid and a base react in the right amounts, both are destroyed and a new substance forms — salt. Salts can be acidic, basic or neutral depending on what they produce when dissolved in water.",
      cards: [
        { icon: "🧂", front: "Neutral salt", back: "e.g. NaCl, K₂SO₄ — no acidic or basic effect." },
        { icon: "🧪", front: "Acidic salt", back: "e.g. NaHCO₃, NaHSO₄ — produces an acidic solution." },
        { icon: "🪨", front: "Basic salt", back: "e.g. CaCO₃, Na₂CO₃ — produces a basic solution." },
      ],
    },
    {
      type: "match",
      id: "salts-match",
      eyebrow: "🎮 Mini-game",
      title: "Match the salt to its type",
      prompt: "Tap a salt, then tap the type it belongs to.",
      pairs: [
        { left: "NaCl", right: "Neutral salt" },
        { left: "K₂SO₄", right: "Neutral salt" },
        { left: "CaCO₃", right: "Basic salt" },
        { left: "NaHCO₃", right: "Acidic salt" },
      ],
    },
    {
      type: "concept",
      id: "salt-naming",
      eyebrow: "🏷️ Naming Salts",
      title: "Salt names come from their parents",
      body: "A salt's name has two parts: the first from its base, the second from its acid. Sulphuric acid gives sulphates, nitric acid gives nitrates, hydrochloric acid gives chlorides, and carbonic acid gives carbonates.",
      cards: [
        { icon: "🧂", front: "NaOH + HCl", back: "→ Sodium chloride" },
        { icon: "🧂", front: "NaOH + H₂SO₄", back: "→ Sodium sulphate" },
        { icon: "🧂", front: "KOH + HNO₃", back: "→ Potassium nitrate" },
      ],
    },
    {
      type: "vocab",
      id: "keywords",
      eyebrow: "🔤 Keywords",
      title: "Words to know",
      words: [
        { word: "Indicator", meaning: "A substance that shows a colour change when it meets an acid or a base." },
        { word: "Acidic substance", meaning: "A substance with a pH below 7." },
        { word: "Basic substance", meaning: "A substance with a pH above 7." },
        { word: "Universal indicator", meaning: "A mixture of indicators that shows a different colour for every pH value." },
        { word: "Natural indicator", meaning: "An indicator obtained from a natural source, like a plant." },
        { word: "Synthetic indicator", meaning: "A man-made (artificial) indicator." },
      ],
    },
    {
      type: "book-question",
      id: "bq-5",
      questionId: "abs-bq-5",
      eyebrow: "📖 Assertion & Reason",
      prompt: "Assertion (A): The reaction between an acid and a base is known as the neutralisation reaction.\nReason (R): The neutralisation reaction forms salt and water as a product.",
      options: [
        { id: "a", label: "Both A and R are true, and R correctly explains A" },
        { id: "b", label: "Both A and R are true, but R does not explain A" },
        { id: "c", label: "A is true, but R is false" },
        { id: "d", label: "A is false, but R is true" },
      ],
      correct: "a",
      explain: "Neutralisation is defined as acid + base forming salt and water — so R is exactly why A is true.",
    },
    {
      type: "quiz",
      id: "boss-quiz",
      eyebrow: "🏆 Boss Quiz",
      title: "Prove you've mastered acids, bases and salts",
      questions: [
        {
          questionId: "abs-quiz-1",
          prompt: "The reaction between an acid and a base gives…",
          options: [
            { id: "a", label: "Only salt" },
            { id: "b", label: "Only water" },
            { id: "c", label: "Only hydrogen" },
            { id: "d", label: "Both salt and water" },
          ],
          correct: "d",
          explain: "Acid + Base → Salt + Water.",
        },
        {
          questionId: "abs-quiz-2",
          prompt: "Which indicator turns pink when a few drops of sodium hydroxide solution are added?",
          options: [
            { id: "a", label: "Blue litmus" },
            { id: "b", label: "Phenolphthalein" },
            { id: "c", label: "Turmeric paper" },
            { id: "d", label: "China rose indicator" },
          ],
          correct: "b",
          explain: "Phenolphthalein is colourless in acid and turns pink in a base.",
        },
        {
          questionId: "abs-quiz-3",
          prompt: "The reaction between an acid and a base to form salt and water is called…",
          options: [
            { id: "a", label: "Carbonation" },
            { id: "b", label: "Hydrogenation" },
            { id: "c", label: "Neutralisation" },
            { id: "d", label: "Titration" },
          ],
          correct: "c",
        },
        {
          questionId: "abs-quiz-4",
          prompt: "What is the common name of sodium chloride?",
          options: [
            { id: "a", label: "Baking powder" },
            { id: "b", label: "Milk of magnesia" },
            { id: "c", label: "Common salt" },
            { id: "d", label: "Methyl orange" },
          ],
          correct: "c",
        },
        {
          questionId: "abs-quiz-5",
          prompt: "Ammonium hydroxide is used at home to remove…",
          options: [
            { id: "a", label: "Rust stains" },
            { id: "b", label: "Ink stains" },
            { id: "c", label: "Oil stains" },
            { id: "d", label: "Paint stains" },
          ],
          correct: "b",
        },
        {
          questionId: "abs-quiz-6",
          prompt: "A base that is soluble in water is called a/an…",
          options: [
            { id: "a", label: "Acid" },
            { id: "b", label: "Alkali" },
            { id: "c", label: "Salt" },
            { id: "d", label: "Indicator" },
          ],
          correct: "b",
        },
        {
          questionId: "abs-quiz-7",
          prompt: "What causes the sharp pain from an ant's sting?",
          options: [
            { id: "a", label: "Acetic acid" },
            { id: "b", label: "Citric acid" },
            { id: "c", label: "Formic acid" },
            { id: "d", label: "Oxalic acid" },
          ],
          correct: "c",
          explain: "An ant's sting injects formic acid into the skin.",
        },
      ],
    },
    {
      type: "concept",
      id: "done",
      eyebrow: "🎉 Chapter Complete",
      title: "You've mastered acids, bases and salts",
      body: "You can now tell an acid from a base, name the indicators that reveal them, and explain why neutralisation matters — from antacids to acid rain. Great work!",
    },
  ],
};
