import type { Chapter } from "../types";

// Class 7 Science Ch. 2 (Nutrition in Animals). Frame: "The Food Journey" —
// follow a bite of food through the body. Stable ids nia-bq-* / nia-quiz-* /
// nia-ex-*.
export const nutritionInAnimalsChapter: Chapter = {
  slug: "nutrition-in-animals",
  title: "Nutrition in Animals",
  subject: "Science",
  emoji: "🍽️",
  color: "#d85a30",
  description: "Follow a bite of food on its journey — from teeth and tongue to the tiny villi — and meet the amoeba, hydra and cud-chewing cow.",
  trophy: { emoji: "🍽️", name: "Golden Fork", caption: "Traced the whole food journey and mastered digestion in animals." },
  scenes: [
    {
      type: "concept",
      id: "hook",
      eyebrow: "🚀 The Food Journey",
      title: "What happens to your breakfast?",
      body: "You take a bite of paratha. Over the next day it's chopped, mashed, dissolved, broken into tiny pieces, absorbed into your blood, and the leftovers pushed out. That whole adventure is DIGESTION — breaking complex, water-insoluble food into simple, water-soluble nutrients your body can absorb. Different animals do it in wonderfully different ways.",
    },
    {
      type: "match",
      id: "food-taking-match",
      eyebrow: "🎮 Everyone Eats Differently",
      title: "Match the animal to how it takes food",
      prompt: "Tap an animal, then tap its special feeding tool.",
      pairs: [
        { left: "Amoeba", right: "False feet (pseudopodia)" },
        { left: "Butterfly", right: "Tube-like proboscis" },
        { left: "Frog", right: "Long sticky tongue" },
        { left: "Hydra", right: "Stinging tentacles" },
      ],
    },
    {
      type: "concept",
      id: "amoeba",
      eyebrow: "🦠 The One-Celled Eater",
      title: "Nutrition in Amoeba",
      body: "Amoeba is a single cell, yet it does everything in that one cell! It senses food, then pushes out finger-like false feet called pseudopodia that surround the food and engulf it into a food vacuole. Enzymes there digest it, nutrients are absorbed, and the vacuole moves to the edge and bursts to throw out waste (egestion).",
    },
    {
      type: "sort",
      id: "digestion-steps-order",
      eyebrow: "🗂️ The Five Steps",
      title: "Building vs breaking?",
      prompt: "Digestion has five steps. Sort each: is it TAKING IN / breaking down, or USING / getting rid?",
      buckets: ["Taking in & breaking", "Using & removing"],
      items: [
        { label: "Ingestion (taking food in)", bucket: 0 },
        { label: "Digestion (breaking it down)", bucket: 0 },
        { label: "Absorption (into the blood)", bucket: 1 },
        { label: "Assimilation (using nutrients)", bucket: 1 },
        { label: "Egestion (removing waste)", bucket: 1 },
      ],
    },
    {
      type: "concept",
      id: "hydra",
      eyebrow: "🐙 The Tentacled Hunter",
      title: "Nutrition in Hydra",
      body: "Hydra lives in fresh water and has a tubular body with tentacles around its mouth. The tentacles carry stinging cells that paralyse tiny prey, then push it into the central body cavity. Digestive juices break it down, cells absorb the nutrients, and undigested bits are egested back out through the same mouth.",
    },
    {
      type: "concept",
      id: "human-steps",
      eyebrow: "👤 The Human Way",
      title: "Five steps in human digestion",
      body: "In humans, food travels a long tube — the alimentary canal — helped by glands. Tap each step in order.",
      cards: [
        { icon: "👄", front: "1 Ingestion", back: "Taking food in through the mouth; teeth and tongue help." },
        { icon: "🔨", front: "2 Digestion", back: "Mechanical + chemical breakdown of complex food into simple, water-soluble bits." },
        { icon: "🩸", front: "3 Absorption", back: "Digested nutrients pass into the bloodstream." },
        { icon: "💪", front: "4 Assimilation", back: "Absorbed food is used for energy, building the body and repairing tissue." },
        { icon: "🚽", front: "5 Egestion", back: "Undigested food is thrown out of the body." },
      ],
    },
    {
      type: "concept",
      id: "mouth-teeth",
      eyebrow: "😁 The Mouth",
      title: "Teeth, tongue and saliva",
      body: "Digestion starts in the mouth (buccal cavity). Teeth break food mechanically; the tongue mixes it with saliva (which contains enzymes that start breaking down starch) into a soft ball called a bolus, ready to swallow. There are four kinds of teeth — tap to learn each job.",
      cards: [
        { icon: "🔪", front: "Incisors", back: "Chisel-shaped front teeth for CUTTING. 8 total, 4 in each jaw." },
        { icon: "🗡️", front: "Canines", back: "Pointed teeth for TEARING. 4 total, one each side of the incisors." },
        { icon: "🪨", front: "Premolars", back: "Flat, strong teeth for CRUSHING. 8 total, 4 in each jaw." },
        { icon: "⚙️", front: "Molars", back: "Broad, flat teeth for GRINDING. 12 total, 3 on each side of each jaw." },
      ],
    },
    {
      type: "book-question",
      id: "bq-1",
      questionId: "nia-bq-1",
      eyebrow: "📖 Practice",
      prompt: "The teeth that are chisel-shaped and help in cutting food are called…",
      options: [
        { id: "a", label: "Canines" },
        { id: "b", label: "Molars" },
        { id: "c", label: "Premolars" },
        { id: "d", label: "Incisors" },
      ],
      correct: "d",
      explain: "Incisors are the chisel-shaped front teeth for cutting.",
    },
    {
      type: "concept",
      id: "tooth-decay",
      eyebrow: "🦷 Tooth Trouble",
      title: "How tooth decay happens",
      body: "If you don't clean your teeth, bacteria feast on leftover sugar and make acid. The acid slowly corrodes the hard enamel and dentine, drilling a cavity. When it reaches the pulp (with the nerve), OUCH — toothache! Prevent it: rinse after meals, brush twice a day, and eat less sugary stuff.",
    },
    {
      type: "concept",
      id: "food-pipe-stomach",
      eyebrow: "🛝 Down the Tube",
      title: "Food pipe and stomach",
      body: "The swallowed bolus travels down the oesophagus (food pipe). Its muscles squeeze in a wave called peristalsis, pushing food along — that's why you can swallow even upside down! The food reaches the stomach, a J-shaped muscular bag that makes dilute hydrochloric acid (which kills germs and helps digest protein) and mucus (which protects the stomach's own wall). The half-digested paste is now called chyme.",
    },
    {
      type: "book-question",
      id: "bq-2",
      questionId: "nia-bq-2",
      eyebrow: "📖 Practice",
      prompt: "The wave-like movement of the oesophagus that pushes food to the stomach is called…",
      options: [
        { id: "a", label: "Peristalsis" },
        { id: "b", label: "Locomotion" },
        { id: "c", label: "Relaxation" },
        { id: "d", label: "Contraction" },
      ],
      correct: "a",
      explain: "Peristalsis is the alternating contraction and relaxation that moves food along the whole canal.",
    },
    {
      type: "concept",
      id: "glands-intestine",
      eyebrow: "🏭 The Helpers",
      title: "Liver, pancreas and the small intestine",
      body: "The chyme enters the small intestine (about 7.5 m long!), where the real magic finishes. Tap the helpers.",
      cards: [
        { icon: "🟤", front: "Liver", back: "The body's largest gland. Makes bile (stored in the gall bladder) that breaks big fat globules into small ones." },
        { icon: "🍦", front: "Pancreas", back: "Secretes pancreatic juice with enzymes (trypsin, amylase, lipase) that digest carbs, proteins and fats." },
        { icon: "🧽", front: "Villi", back: "Millions of tiny finger-like projections lining the small intestine — they hugely increase surface area to absorb nutrients into the blood." },
      ],
    },
    {
      type: "concept",
      id: "large-intestine",
      eyebrow: "🔚 The Final Stop",
      title: "Large intestine and egestion",
      body: "Whatever the small intestine doesn't absorb moves into the large intestine (wider and shorter, ~1.5 m). Here extra water and salts are absorbed, leaving semi-solid faecal matter that's stored in the rectum and finally removed through the anus — the process of egestion.",
    },
    {
      type: "concept",
      id: "ruminants",
      eyebrow: "🐄 The Grass Machines",
      title: "Digestion in ruminants",
      body: "Cows, buffaloes, sheep and goats eat grass, which is full of cellulose that humans can't digest. Their stomach has FOUR chambers. They quickly swallow grass into the rumen, where microorganisms start breaking down the cellulose. Later they bring the half-digested food (the cud) back up to the mouth and chew it again — this is rumination (chewing the cud). Animals that do this are called ruminants.",
    },
    {
      type: "book-question",
      id: "bq-3",
      questionId: "nia-bq-3",
      eyebrow: "📖 Practice",
      prompt: "An animal which has no mouth and no digestive system is…",
      options: [
        { id: "a", label: "Antelope" },
        { id: "b", label: "Amoeba" },
        { id: "c", label: "Alligator" },
        { id: "d", label: "Angora goat" },
      ],
      correct: "b",
      explain: "Amoeba is a single cell — it does everything in that one cell, with no mouth or gut.",
    },
    {
      type: "vocab",
      id: "keywords",
      eyebrow: "🔤 Digestion Glossary",
      title: "Words to know",
      words: [
        { word: "Ingestion", meaning: "The process of taking food into the body." },
        { word: "Digestion", meaning: "Breaking complex food into simple, water-soluble substances." },
        { word: "Absorption", meaning: "Digested nutrients passing into the bloodstream." },
        { word: "Assimilation", meaning: "Using the absorbed food for energy, growth and repair." },
        { word: "Egestion", meaning: "Removing undigested waste from the body." },
        { word: "Peristalsis", meaning: "The wave-like muscle movement that pushes food along the canal." },
        { word: "Villi", meaning: "Finger-like projections in the small intestine that absorb nutrients." },
        { word: "Pseudopodia", meaning: "The false feet an amoeba uses to engulf food." },
        { word: "Rumination", meaning: "Chewing the cud — bringing food back up to re-chew (in cattle)." },
        { word: "Cellulose", meaning: "A complex carbohydrate in grass that ruminants (not humans) can digest." },
      ],
    },
    {
      type: "quiz",
      id: "boss-quiz",
      eyebrow: "🏆 Boss Quiz",
      title: "The Food Journey — final challenge",
      questions: [
        {
          questionId: "nia-quiz-1",
          prompt: "The digestive juices in the ___ help in the digestion of proteins.",
          options: [
            { id: "a", label: "Mouth" },
            { id: "b", label: "Stomach" },
            { id: "c", label: "Small intestine" },
            { id: "d", label: "Large intestine" },
          ],
          correct: "b",
          explain: "The stomach's hydrochloric acid and juices begin protein digestion.",
        },
        {
          questionId: "nia-quiz-2",
          prompt: "Which of the following is digested by saliva?",
          options: [
            { id: "a", label: "Glucose" },
            { id: "b", label: "Starch" },
            { id: "c", label: "Cellulose" },
            { id: "d", label: "Proteins" },
          ],
          correct: "b",
          explain: "Saliva contains an enzyme that starts breaking starch into sugar.",
        },
        {
          questionId: "nia-quiz-3",
          prompt: "Mucus, hydrochloric acid and digestive juices are secreted by the inner lining of the…",
          options: [
            { id: "a", label: "Pancreas" },
            { id: "b", label: "Stomach" },
            { id: "c", label: "Small intestine" },
            { id: "d", label: "Salivary glands" },
          ],
          correct: "b",
        },
        {
          questionId: "nia-quiz-4",
          prompt: "The site of complete digestion and absorption of food in humans is the…",
          options: [
            { id: "a", label: "Stomach" },
            { id: "b", label: "Small intestine" },
            { id: "c", label: "Rectum" },
            { id: "d", label: "Large intestine" },
          ],
          correct: "b",
          explain: "Most digestion finishes in the small intestine, and villi absorb the nutrients there.",
        },
        {
          questionId: "nia-quiz-5",
          prompt: "The teeth used for piercing and tearing food are called…",
          options: [
            { id: "a", label: "Incisors" },
            { id: "b", label: "Canines" },
            { id: "c", label: "Molars" },
            { id: "d", label: "Premolars" },
          ],
          correct: "b",
        },
        {
          questionId: "nia-quiz-6",
          prompt: "In humans, the 16 teeth of each jaw consist of…",
          options: [
            { id: "a", label: "2 incisors, 4 canines, 4 premolars and 6 molars" },
            { id: "b", label: "4 incisors, 2 canines, 6 premolars and 4 molars" },
            { id: "c", label: "4 incisors, 2 canines, 4 premolars and 6 molars" },
            { id: "d", label: "2 incisors, 4 canines, 6 premolars and 4 molars" },
          ],
          correct: "c",
          explain: "Per jaw: 4 incisors + 2 canines + 4 premolars + 6 molars = 16 (32 in all).",
        },
        {
          questionId: "nia-quiz-7",
          prompt: "Which carbohydrate can be digested by a cow but not by a human?",
          options: [
            { id: "a", label: "Glucose" },
            { id: "b", label: "Cellulose" },
            { id: "c", label: "Starch" },
            { id: "d", label: "Cane sugar" },
          ],
          correct: "b",
          explain: "Rumen microorganisms let cows digest cellulose; humans cannot.",
        },
      ],
    },
    {
      type: "concept",
      id: "exercise-pointer",
      eyebrow: "📚 Homework Zone",
      title: "Full exercises are in your Practice Arena",
      body: "Every MCQ from the chapter exercise is waiting in the Practice Arena under Nutrition in Animals — where XP, streaks and Today's Review all count.",
    },
    {
      type: "concept",
      id: "done",
      eyebrow: "🎉 Chapter Complete",
      title: "The whole journey, mastered",
      body: "You followed food from the mouth to the villi, met the amoeba's false feet, the hydra's tentacles and the cow's four-chambered stomach. The Golden Fork is yours!",
    },
  ],
  exercises: [
    {
      questionId: "nia-ex-1",
      prompt: "The teeth that are chisel-shaped and help in cutting food are called…",
      options: [
        { id: "a", label: "Canines" },
        { id: "b", label: "Molars" },
        { id: "c", label: "Premolars" },
        { id: "d", label: "Incisors" },
      ],
      correct: "d",
    },
    {
      questionId: "nia-ex-2",
      prompt: "The alternate movement of the oesophagus to pass food into the stomach is called…",
      options: [
        { id: "a", label: "Peristalsis" },
        { id: "b", label: "Locomotion" },
        { id: "c", label: "Relaxation" },
        { id: "d", label: "Contraction" },
      ],
      correct: "a",
    },
    {
      questionId: "nia-ex-3",
      prompt: "An animal which has no mouth and no digestive system is…",
      options: [
        { id: "a", label: "Antelope" },
        { id: "b", label: "Amoeba" },
        { id: "c", label: "Alligator" },
        { id: "d", label: "Angora goat" },
      ],
      correct: "b",
    },
    {
      questionId: "nia-ex-4",
      prompt: "Which of the following is digested by saliva?",
      options: [
        { id: "a", label: "Glucose" },
        { id: "b", label: "Starch" },
        { id: "c", label: "Cellulose" },
        { id: "d", label: "Proteins" },
      ],
      correct: "b",
    },
    {
      questionId: "nia-ex-5",
      prompt: "Mucus, hydrochloric acid and digestive juices are secreted by the inner lining of the…",
      options: [
        { id: "a", label: "Pancreas" },
        { id: "b", label: "Stomach" },
        { id: "c", label: "Small intestine" },
        { id: "d", label: "Salivary glands" },
      ],
      correct: "b",
    },
    {
      questionId: "nia-ex-6",
      prompt: "The site of complete digestion and absorption of food in humans is the…",
      options: [
        { id: "a", label: "Stomach" },
        { id: "b", label: "Small intestine" },
        { id: "c", label: "Rectum" },
        { id: "d", label: "Large intestine" },
      ],
      correct: "b",
    },
    {
      questionId: "nia-ex-7",
      prompt: "The amino acids present in digested food are used by our body to make…",
      options: [
        { id: "a", label: "Fats" },
        { id: "b", label: "Proteins" },
        { id: "c", label: "Minerals" },
        { id: "d", label: "Carbohydrates" },
      ],
      correct: "b",
      explain: "Amino acids are the building blocks of proteins.",
    },
    {
      questionId: "nia-ex-8",
      prompt: "The teeth in our mouth used for piercing and tearing food are called…",
      options: [
        { id: "a", label: "Incisors" },
        { id: "b", label: "Canines" },
        { id: "c", label: "Molars" },
        { id: "d", label: "Premolars" },
      ],
      correct: "b",
    },
    {
      questionId: "nia-ex-9",
      prompt: "The largest gland in the body is the…",
      options: [
        { id: "a", label: "Pancreas" },
        { id: "b", label: "Liver" },
        { id: "c", label: "Salivary gland" },
        { id: "d", label: "Gall bladder" },
      ],
      correct: "b",
    },
    {
      questionId: "nia-ex-10",
      prompt: "The inner wall of the small intestine has many finger-like projections called…",
      options: [
        { id: "a", label: "Pseudopodia" },
        { id: "b", label: "Villi" },
        { id: "c", label: "Tentacles" },
        { id: "d", label: "Stomata" },
      ],
      correct: "b",
    },
    {
      questionId: "nia-ex-11",
      prompt: "The partially digested food brought back from a ruminant's stomach to be re-chewed is called…",
      options: [
        { id: "a", label: "Chyme" },
        { id: "b", label: "Bolus" },
        { id: "c", label: "Cud" },
        { id: "d", label: "Bile" },
      ],
      correct: "c",
    },
    {
      questionId: "nia-ex-12",
      prompt: "Assertion: The incisor, canine, premolar and molar are the four types of teeth present in the mouth. Reason: There are four types of teeth present in the mouth.",
      options: [
        { id: "a", label: "Both A and R true, R explains A" },
        { id: "b", label: "Both A and R true, R does not explain A" },
        { id: "c", label: "A is true, R is false" },
        { id: "d", label: "A is false, R is true" },
      ],
      correct: "b",
      explain: "Both statements are true and essentially the same fact, so R restates rather than explains A.",
    },
    {
      questionId: "nia-ex-13",
      prompt: "Amoeba digests its food in the…",
      options: [
        { id: "a", label: "Stomach" },
        { id: "b", label: "Food vacuole" },
        { id: "c", label: "Mouth" },
        { id: "d", label: "Small intestine" },
      ],
      correct: "b",
    },
    // ——— True / False ———
    {
      questionId: "nia-tf-1",
      prompt: "True or False: Hydra lives in marine (sea) water.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "b",
      explain: "Hydra lives in fresh water.",
    },
    {
      questionId: "nia-tf-2",
      prompt: "True or False: Villi increase the surface area of the small intestine for absorption.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    {
      questionId: "nia-tf-3",
      prompt: "True or False: Most of the digestion of food takes place in the stomach.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "b",
      explain: "Most digestion and absorption happens in the small intestine.",
    },
    {
      questionId: "nia-tf-4",
      prompt: "True or False: The oesophagus moves food by a wave-like motion called peristalsis.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    {
      questionId: "nia-tf-5",
      prompt: "True or False: Cows can digest cellulose but humans cannot.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
      explain: "Microorganisms in the cow's rumen digest cellulose; humans have no such helpers.",
    },
    // ——— Fill in the blanks ———
    {
      questionId: "nia-fb-1",
      prompt: "The largest gland in the human body is the ______.",
      qtype: "fill-blank",
      answers: ["liver"],
    },
    {
      questionId: "nia-fb-2",
      prompt: "The finger-like projections in the small intestine that absorb nutrients are called ______.",
      qtype: "fill-blank",
      answers: ["villi", "villus"],
    },
    {
      questionId: "nia-fb-3",
      prompt: "Amoeba takes in food using its false feet, called ______.",
      qtype: "fill-blank",
      answers: ["pseudopodia", "pseudopod", "pseudopodium"],
    },
    {
      questionId: "nia-fb-4",
      prompt: "The partially digested food a cow brings back to the mouth to chew again is called the ______.",
      qtype: "fill-blank",
      answers: ["cud"],
    },
    {
      questionId: "nia-fb-5",
      prompt: "The removal of undigested food from the body is called ______.",
      qtype: "fill-blank",
      answers: ["egestion"],
    },
  ],
};
