import type { Chapter } from "../types";

// Class 7 Science Ch. 1 (Nutrition in Plants). Frame: "The Green Kitchen" —
// plants are chefs; some cook their own food, some steal it. Stable ids
// nip-bq-* / nip-quiz-* / nip-ex-*.
export const nutritionInPlantsChapter: Chapter = {
  slug: "nutrition-in-plants",
  title: "Nutrition in Plants",
  subject: "Science",
  emoji: "🌿",
  color: "#1db88a",
  description: "Meet the plants that cook their own food in sunlight — and the sneaky ones that steal, trap and share instead.",
  trophy: { emoji: "🌿", name: "Green Chef's Hat", caption: "Mastered how every plant — chef, thief or trapper — gets its food." },
  scenes: [
    {
      type: "concept",
      id: "hook",
      eyebrow: "🍳 The Green Kitchen",
      title: "Every plant is running a kitchen",
      body: "You eat food to live, grow, repair worn-out cells and get energy. Plants need food for exactly the same reasons — but here's the astonishing part: most plants COOK THEIR OWN, out of thin air, water and sunlight. A few sneaky ones can't, so they steal, trap or share. Let's tour the kitchen.",
    },
    {
      type: "concept",
      id: "two-modes",
      eyebrow: "📖 Two Ways to Eat",
      title: "Autotrophs and heterotrophs",
      body: "Nutrition is how living things get and use nutrients. Tap the cards to meet the two great families.",
      cards: [
        { icon: "☀️", front: "Autotroph", back: "Makes its OWN food (auto = self). All green plants are autotrophs — also called producers." },
        { icon: "🍽️", front: "Heterotroph", back: "Gets food from OTHER organisms (hetero = other). Animals, fungi, and some plants." },
        { icon: "🟢", front: "The green clue", back: "The green colour is a pigment called chlorophyll — the secret ingredient that lets a plant cook with sunlight." },
      ],
    },
    {
      type: "concept",
      id: "photosynthesis",
      eyebrow: "🌞 The Recipe",
      title: "Photosynthesis: cooking with light",
      body: "Photo = light, synthesis = making. Green plants combine carbon dioxide and water, using sunlight trapped by chlorophyll, to make glucose (food) — and breathe out oxygen as a bonus. The recipe:\n\nCarbon dioxide + Water → (sunlight + chlorophyll) → Glucose + Oxygen",
      cards: [
        { icon: "🌬️", front: "Carbon dioxide", back: "Absorbed from the air through tiny pores called stomata on the underside of leaves." },
        { icon: "💧", front: "Water", back: "Absorbed from the soil by the roots and carried up to the leaves." },
        { icon: "🟢", front: "Chlorophyll", back: "The green pigment inside disc-like chloroplasts — it captures the sunlight's energy." },
        { icon: "💨", front: "Oxygen", back: "Released as a by-product — the very oxygen other living beings breathe to survive!" },
      ],
    },
    {
      type: "match",
      id: "raw-materials-match",
      eyebrow: "🎮 Sourcing the Ingredients",
      title: "Where does each ingredient come from?",
      prompt: "Tap an ingredient, then tap where the plant gets it.",
      pairs: [
        { left: "Carbon dioxide", right: "From the air (via stomata)" },
        { left: "Water", right: "From the soil (via roots)" },
        { left: "Sunlight", right: "Captured by chlorophyll" },
        { left: "Chlorophyll", right: "Inside the chloroplasts" },
      ],
    },
    {
      type: "concept",
      id: "stomata",
      eyebrow: "🚪 Tiny Doors",
      title: "Stomata: the leaf's breathing pores",
      body: "The underside of a leaf is dotted with minute openings called stomata, each guarded by two bean-shaped guard cells. When the guard cells fill with water they swell and become turgid, pulling the pore OPEN so gases can pass. When water is lost they go flaccid and the pore CLOSES. Carbon dioxide in, oxygen out — all through these little doors.",
    },
    {
      type: "book-question",
      id: "bq-1",
      questionId: "nip-bq-1",
      eyebrow: "📖 Practice",
      prompt: "The disc-like structures in leaf cells that carry out photosynthesis are called…",
      options: [
        { id: "a", label: "Centrioles" },
        { id: "b", label: "Chloroplasts" },
        { id: "c", label: "Mitochondria" },
        { id: "d", label: "Vacuoles" },
      ],
      correct: "b",
      explain: "Chloroplasts contain the green pigment chlorophyll and are where photosynthesis happens.",
    },
    {
      type: "concept",
      id: "starch-test",
      eyebrow: "🔬 Activity: The Starch Test",
      title: "Catching a leaf in the act",
      body: "The glucose a plant makes is quickly stored as starch. We can PROVE a leaf has been photosynthesising by testing for starch: keep a plant in the dark 24–48 hrs (leaf A, the control), then put it in sunlight and pluck leaf B. Boil both in water, then in alcohol to remove the green chlorophyll, then add iodine. Leaf A stays the same; leaf B turns blue-black — starch is present!",
    },
    {
      type: "book-question",
      id: "bq-2",
      questionId: "nip-bq-2",
      eyebrow: "📖 Practice",
      prompt: "When iodine is dropped on a decolourised green leaf, a blue-black colour appears. This shows the leaf contains…",
      options: [
        { id: "a", label: "Glucose" },
        { id: "b", label: "Cellulose" },
        { id: "c", label: "Starch" },
        { id: "d", label: "Sucrose" },
      ],
      correct: "c",
      explain: "Iodine turns blue-black with starch — proof that photosynthesis took place.",
    },
    {
      type: "concept",
      id: "heterotroph-intro",
      eyebrow: "🕵️ The Food Thieves",
      title: "Plants that can't cook",
      body: "Some plants lack chlorophyll, so they can't make their own food. These heterotrophic plants get their meals in four clever ways — tap each card, then we'll meet them.",
      cards: [
        { icon: "🧛", front: "Parasitic", back: "Steal food from a living host plant (e.g. Cuscuta / amarbel)." },
        { icon: "🍄", front: "Saprophytic", back: "Feed on dead and decaying matter (e.g. fungi, mushrooms)." },
        { icon: "🪰", front: "Insectivorous", back: "Trap and digest insects for nitrogen (e.g. Venus flytrap, pitcher plant)." },
        { icon: "🤝", front: "Symbiotic", back: "Share a mutually helpful life with another organism (e.g. lichens)." },
      ],
    },
    {
      type: "concept",
      id: "parasites",
      eyebrow: "🧛 Parasites",
      title: "The freeloaders",
      body: "A parasite takes food from a host, harming it. Cuscuta (amarbel) has no chlorophyll and sinks special roots called haustoria into the host to suck its food — a complete parasite. Mistletoe is a partial parasite: it has green leaves and makes some of its own food, taking mainly water and minerals. Rafflesia is a complete parasite that makes the world's largest flower.",
    },
    {
      type: "concept",
      id: "insectivores",
      eyebrow: "🪰 The Traps",
      title: "Plants that eat animals",
      body: "Some plants grow in nitrogen-poor soil, so they get nitrogen by trapping insects. They lure prey with nectar, colour and scent — then spring the trap. Tap the hunters.",
      cards: [
        { icon: "🪤", front: "Venus flytrap", back: "Two hinged flaps with trigger hairs snap shut when an insect lands." },
        { icon: "🏺", front: "Pitcher plant", back: "A leaf shaped like a pitcher, half-full of liquid, with a slippery slope — insects slip in and are digested." },
        { icon: "🌟", front: "Sundew", back: "Tentacles covered in sticky mucous fold inward around a trapped insect." },
      ],
    },
    {
      type: "sort",
      id: "nutrition-mode-sort",
      eyebrow: "🗂️ Sort the Plants",
      title: "How does each plant eat?",
      prompt: "Sort each plant into how it gets its food.",
      buckets: ["Makes own food ☀️", "Gets food another way 🍽️"],
      items: [
        { label: "Mango tree", bucket: 0 },
        { label: "Cuscuta (amarbel)", bucket: 1 },
        { label: "Grass", bucket: 0 },
        { label: "Pitcher plant", bucket: 1 },
        { label: "Rose bush", bucket: 0 },
        { label: "Mushroom", bucket: 1 },
      ],
    },
    {
      type: "concept",
      id: "symbiosis",
      eyebrow: "🤝 Partners for Life",
      title: "Symbiosis: helping each other",
      body: "Symbiosis is a relationship where BOTH organisms benefit — unlike parasitism, where one harms the other. The classic example is a lichen: an alga and a fungus living as one. The alga has chlorophyll and makes food by photosynthesis; the fungus provides shelter and soaks up water and minerals. Neither could thrive alone.",
    },
    {
      type: "book-question",
      id: "bq-3",
      questionId: "nip-bq-3",
      eyebrow: "📖 Practice",
      prompt: "Which of the following shows symbiosis?",
      options: [
        { id: "a", label: "Alga and fungus" },
        { id: "b", label: "Alga and fish" },
        { id: "c", label: "Rhizobium and pea plant" },
        { id: "d", label: "Both (a) and (c)" },
      ],
      correct: "d",
      explain: "Lichens (alga + fungus) AND Rhizobium living in pea-plant roots are both mutually beneficial — symbiosis.",
    },
    {
      type: "concept",
      id: "soil-nutrients",
      eyebrow: "🌾 Refilling the Soil",
      title: "Rhizobium and the nitrogen trick",
      body: "Plants slowly use up soil nutrients like nitrogen. Plants can't absorb nitrogen from the air directly — but leguminous crops (peas, beans, pulses) have nodules in their roots housing Rhizobium bacteria, which convert air nitrogen into a form roots CAN absorb. The plant feeds the bacteria; the bacteria fertilise the plant — symbiosis again! That's why farmers alternate legumes with cereal crops to restore fertility.",
    },
    {
      type: "book-question",
      id: "bq-4",
      questionId: "nip-bq-4",
      eyebrow: "📖 Practice",
      prompt: "The mineral needed by plants to make proteins is…",
      options: [
        { id: "a", label: "Neon" },
        { id: "b", label: "Iodine" },
        { id: "c", label: "Nitrogen" },
        { id: "d", label: "Calcium" },
      ],
      correct: "c",
      explain: "Proteins are nitrogenous — plants get nitrogen from the soil (thanks to bacteria like Rhizobium).",
    },
    {
      type: "vocab",
      id: "keywords",
      eyebrow: "🔤 Green Glossary",
      title: "Words to know",
      words: [
        { word: "Nutrition", meaning: "The process by which living organisms obtain nutrients." },
        { word: "Autotroph", meaning: "An organism that prepares its own food (all green plants)." },
        { word: "Heterotroph", meaning: "An organism that gets food from other organisms." },
        { word: "Photosynthesis", meaning: "Making food from CO₂ and water using sunlight and chlorophyll." },
        { word: "Chlorophyll", meaning: "The green pigment in chloroplasts that captures sunlight." },
        { word: "Stomata", meaning: "Minute pores on the underside of leaves for gas exchange." },
        { word: "Haustoria", meaning: "The absorbing roots a parasite like Cuscuta sinks into its host." },
        { word: "Saprotroph", meaning: "A plant that feeds on dead and decaying organic matter." },
        { word: "Parasite", meaning: "An organism that lives on a host, harming it, to get food." },
        { word: "Symbiosis", meaning: "A relationship that benefits both organisms involved." },
      ],
    },
    {
      type: "quiz",
      id: "boss-quiz",
      eyebrow: "🏆 Boss Quiz",
      title: "Green Kitchen — final tasting",
      questions: [
        {
          questionId: "nip-quiz-1",
          prompt: "Gases like carbon dioxide and oxygen are exchanged through the…",
          options: [
            { id: "a", label: "Vacuoles" },
            { id: "b", label: "Spiracles" },
            { id: "c", label: "Stomata" },
            { id: "d", label: "Roots" },
          ],
          correct: "c",
        },
        {
          questionId: "nip-quiz-2",
          prompt: "Plants that make their own food are known as…",
          options: [
            { id: "a", label: "Saprophytes" },
            { id: "b", label: "Parasites" },
            { id: "c", label: "Autotrophs" },
            { id: "d", label: "Heterotrophs" },
          ],
          correct: "c",
        },
        {
          questionId: "nip-quiz-3",
          prompt: "Cuscuta is an example of a…",
          options: [
            { id: "a", label: "Autotroph" },
            { id: "b", label: "Parasite" },
            { id: "c", label: "Saprotroph" },
            { id: "d", label: "Host" },
          ],
          correct: "b",
          explain: "Cuscuta has no chlorophyll and sucks food from a host plant.",
        },
        {
          questionId: "nip-quiz-4",
          prompt: "The process of photosynthesis converts solar energy into…",
          options: [
            { id: "a", label: "Kinetic energy" },
            { id: "b", label: "Chemical energy" },
            { id: "c", label: "Potential energy" },
            { id: "d", label: "Nuclear energy" },
          ],
          correct: "b",
          explain: "Sunlight's energy is stored as chemical energy in glucose.",
        },
        {
          questionId: "nip-quiz-5",
          prompt: "The simplest food produced during photosynthesis is…",
          options: [
            { id: "a", label: "Starch" },
            { id: "b", label: "Cellulose" },
            { id: "c", label: "Glucose" },
            { id: "d", label: "Sucrose" },
          ],
          correct: "c",
          explain: "Glucose is the simple sugar made first; it's then stored as starch.",
        },
        {
          questionId: "nip-quiz-6",
          prompt: "Which plant has a heterotrophic mode of nutrition?",
          options: [
            { id: "a", label: "Money plant" },
            { id: "b", label: "Croton plant" },
            { id: "c", label: "Cuscuta plant" },
            { id: "d", label: "Alga" },
          ],
          correct: "c",
        },
        {
          questionId: "nip-quiz-7",
          prompt: "The bacteria that convert air nitrogen into a usable form live in the roots of…",
          options: [
            { id: "a", label: "Cereal crops (wheat, rice)" },
            { id: "b", label: "Leguminous crops (peas, beans)" },
            { id: "c", label: "Cactus" },
            { id: "d", label: "Money plant" },
          ],
          correct: "b",
          explain: "Rhizobium lives in the root nodules of legumes.",
        },
      ],
    },
    {
      type: "concept",
      id: "exercise-pointer",
      eyebrow: "📚 Homework Zone",
      title: "Full exercises are in your Practice Arena",
      body: "Every MCQ and fill-in from the chapter exercise lives in the Practice Arena under Nutrition in Plants — where XP, streaks and Today's Review all count.",
    },
    {
      type: "concept",
      id: "done",
      eyebrow: "🎉 Chapter Complete",
      title: "You've mastered the Green Kitchen",
      body: "You now know how green plants cook with sunlight, how the sneaky parasites, trappers and saprophytes get their meals, and how Rhizobium keeps the soil rich. The Green Chef's Hat is yours!",
    },
  ],
  exercises: [
    {
      questionId: "nip-ex-1",
      prompt: "The special disc-like structures in leaf cells that carry out photosynthesis are called…",
      options: [
        { id: "a", label: "Centrioles" },
        { id: "b", label: "Chloroplasts" },
        { id: "c", label: "Mitochondria" },
        { id: "d", label: "Vacuoles" },
      ],
      correct: "b",
    },
    {
      questionId: "nip-ex-2",
      prompt: "Cuscuta is an example of a…",
      options: [
        { id: "a", label: "Autotroph" },
        { id: "b", label: "Parasite" },
        { id: "c", label: "Saprotroph" },
        { id: "d", label: "Host" },
      ],
      correct: "b",
    },
    {
      questionId: "nip-ex-3",
      prompt: "The process by which living organisms obtain nutrients for growth is called…",
      options: [
        { id: "a", label: "Respiration" },
        { id: "b", label: "Nutrition" },
        { id: "c", label: "Digestion" },
        { id: "d", label: "Transpiration" },
      ],
      correct: "b",
    },
    {
      questionId: "nip-ex-4",
      prompt: "Plants which obtain nutrition from dead and decaying organic matter are called…",
      options: [
        { id: "a", label: "Parasites" },
        { id: "b", label: "Autotrophs" },
        { id: "c", label: "Saprotrophs" },
        { id: "d", label: "Hosts" },
      ],
      correct: "c",
    },
    {
      questionId: "nip-ex-5",
      prompt: "Lichens have which two organisms as symbiotic partners?",
      options: [
        { id: "a", label: "Alga and fungus" },
        { id: "b", label: "Alga and bacteria" },
        { id: "c", label: "Fungus and moss" },
        { id: "d", label: "Bacteria and fungus" },
      ],
      correct: "a",
    },
    {
      questionId: "nip-ex-6",
      prompt: "An autotrophic plant that also traps insects is best described as…",
      options: [
        { id: "a", label: "A pure autotroph" },
        { id: "b", label: "A pure parasite" },
        { id: "c", label: "A partial heterotroph" },
        { id: "d", label: "A saprophyte" },
      ],
      correct: "c",
      explain: "Insectivorous plants photosynthesise AND trap insects for nitrogen — partly heterotrophic.",
    },
    {
      questionId: "nip-ex-7",
      prompt: "Assertion: Some green plants are also insectivorous. Reason: Insectivorous plants cannot synthesise their own food.",
      options: [
        { id: "a", label: "Both A and R true, R explains A" },
        { id: "b", label: "Both A and R true, R does not explain A" },
        { id: "c", label: "A is true, R is false" },
        { id: "d", label: "A is false, R is true" },
      ],
      correct: "c",
      explain: "Green insectivorous plants CAN photosynthesise (A true); they trap insects only for nitrogen, so R is false.",
    },
    {
      questionId: "nip-ex-8",
      prompt: "Assertion: All plants are autotrophic. Reason: Heterotrophic plants cannot synthesise their own food.",
      options: [
        { id: "a", label: "Both A and R true, R explains A" },
        { id: "b", label: "Both A and R true, R does not explain A" },
        { id: "c", label: "A is true, R is false" },
        { id: "d", label: "A is false, R is true" },
      ],
      correct: "d",
      explain: "Not all plants are autotrophic — parasites and saprophytes exist (A false); R is true.",
    },
    {
      questionId: "nip-ex-9",
      prompt: "Consider: Lichen, Mushroom, Cuscuta, Grass, Pitcher plant. Cuscuta is…",
      options: [
        { id: "a", label: "An autotroph" },
        { id: "b", label: "A saprophyte" },
        { id: "c", label: "A symbiotic plant" },
        { id: "d", label: "A parasite" },
      ],
      correct: "d",
    },
    {
      questionId: "nip-ex-10",
      prompt: "Which of these prepares its own food?",
      options: [
        { id: "a", label: "Mushroom" },
        { id: "b", label: "Cuscuta" },
        { id: "c", label: "Grass" },
        { id: "d", label: "Pitcher plant (for its food)" },
      ],
      correct: "c",
      explain: "Grass is a green autotroph; the others depend on outside sources.",
    },
    {
      questionId: "nip-ex-11",
      prompt: "The special roots through which Cuscuta sucks food from its host are called…",
      options: [
        { id: "a", label: "Haustoria" },
        { id: "b", label: "Stomata" },
        { id: "c", label: "Root nodules" },
        { id: "d", label: "Root hairs" },
      ],
      correct: "a",
    },
    {
      questionId: "nip-ex-12",
      prompt: "Green plants are also called…",
      options: [
        { id: "a", label: "Consumers" },
        { id: "b", label: "Producers" },
        { id: "c", label: "Decomposers" },
        { id: "d", label: "Parasites" },
      ],
      correct: "b",
      explain: "Autotrophs produce food for themselves and every other organism — they're producers.",
    },
  ],
};
