import type { Chapter } from "../types";

// Class 7 Maths Ch. 5 (textbook pages 99–117) — built around "Line City":
// every crossing hides secrets (equal angles, hidden letters F/Z/C), and the
// student earns each rule by driving the simulations. Tracked ids pil-bq-* /
// pil-quiz-* are stable — never reuse for different questions.
export const parallelIntersectingLinesChapter: Chapter = {
  slug: "parallel-intersecting-lines",
  title: "Parallel and Intersecting Lines",
  subject: "Maths",
  emoji: "📐",
  color: "#6c63ff",
  description: "Spin angles, crack the scissors code, hunt the hidden letters F, Z and C, and judge which lines can never meet.",
  trophy: { emoji: "📐", name: "Golden Protractor", caption: "Hunted every hidden letter and judged every line in Line City." },
  scenes: [
    {
      type: "concept",
      id: "hook",
      eyebrow: "🏙️ Welcome to Line City",
      title: "Lines are running your life",
      body: "Railway tracks that never meet. Scissor blades that cross. The letter T in a signboard, standing perfectly upright. Every pair of lines in the world is playing by secret rules — and by the end of this chapter you'll know them all: which lines meet, which never can, and the hidden letters that reveal every angle's value.",
    },
    {
      type: "match",
      id: "spot-lines-match",
      eyebrow: "🎮 Spot the Pair",
      title: "What kind of line pair is it?",
      prompt: "Tap a real thing, then tap the kind of line pair it shows.",
      pairs: [
        { left: "Railway track", right: "Parallel lines" },
        { left: "Open scissor blades", right: "Intersecting lines" },
        { left: "The letter T", right: "Perpendicular lines" },
        { left: "Ruler's two long edges", right: "Parallel lines" },
        { left: "Two crossing roads", right: "Intersecting lines" },
        { left: "Flagstaff on the ground", right: "Perpendicular lines" },
      ],
    },
    {
      type: "concept",
      id: "pair-of-lines",
      eyebrow: "📖 The Three Pairs",
      title: "Intersecting, perpendicular, parallel",
      body: "Tap each card — and meet the two symbols mathematicians use.",
      cards: [
        { icon: "✂️", front: "Intersecting", back: "Cross each other at exactly one point — the point of intersection. Like scissor blades!" },
        { icon: "🚩", front: "Perpendicular", back: "Intersect at exactly 90°. Symbol: ⊥ (p ⊥ q). A square corner marks the right angle." },
        { icon: "🛤️", front: "Parallel", back: "Never meet, however far you extend them — always the same distance apart. Symbol: ∥ (p ∥ q)." },
      ],
    },
    { type: "custom", id: "angle-tuner", component: "angle-tuner" },
    {
      type: "sort",
      id: "angle-type-sort",
      eyebrow: "🗂️ Sort It",
      title: "Acute or obtuse?",
      prompt: "Less than 90° = acute. Between 90° and 180° = obtuse. Sort them!",
      buckets: ["Acute 🤏", "Obtuse 🦅"],
      items: [
        { label: "35°", bucket: 0 },
        { label: "120°", bucket: 1 },
        { label: "89°", bucket: 0 },
        { label: "91°", bucket: 1 },
        { label: "45°", bucket: 0 },
        { label: "175°", bucket: 1 },
      ],
    },
    { type: "custom", id: "angle-partners", component: "angle-partners" },
    {
      type: "book-question",
      id: "bq-1",
      questionId: "pil-bq-1",
      eyebrow: "📖 Practice",
      prompt: "The complement of 35° is…",
      options: [
        { id: "a", label: "55°" },
        { id: "b", label: "65°" },
        { id: "c", label: "145°" },
        { id: "d", label: "45°" },
      ],
      correct: "a",
      explain: "Complements add to 90°: 90° − 35° = 55°.",
    },
    {
      type: "book-question",
      id: "bq-2",
      questionId: "pil-bq-2",
      eyebrow: "📖 Practice (algebra!)",
      prompt: "∠A and ∠B are complementary. If ∠A = (7 + 4x)° and ∠B = (x + 23)°, find x.",
      options: [
        { id: "a", label: "x = 8" },
        { id: "b", label: "x = 10" },
        { id: "c", label: "x = 12" },
        { id: "d", label: "x = 15" },
      ],
      correct: "c",
      explain: "7 + 4x + x + 23 = 90 → 5x + 30 = 90 → 5x = 60 → x = 12.",
    },
    { type: "custom", id: "scissors-sim", component: "scissors-sim" },
    {
      type: "concept",
      id: "angle-pairs",
      eyebrow: "📖 Naming What You Found",
      title: "The angle pairs of every crossing",
      body: "The scissors showed you the rules — here are their official names. Tap each card.",
      cards: [
        { icon: "🤝", front: "Adjacent angles", back: "Share a vertex and a common arm, with no overlap — they sit 'next to' each other." },
        { icon: "📏", front: "Linear pair", back: "Adjacent angles whose outer arms form a straight line. Always add to 180°." },
        { icon: "❌", front: "Vertically opposite", back: "The angles facing each other across a crossing. Always EQUAL." },
        { icon: "🎡", front: "Angles at a point", back: "All the angles around one point always add to 360° — one full rotation." },
      ],
    },
    {
      type: "book-question",
      id: "bq-3",
      questionId: "pil-bq-3",
      eyebrow: "📖 Practice (from Example 7)",
      prompt: "Three angles on a straight line measure (x + 31)°, (x + 20)° and x°. Find x.",
      options: [
        { id: "a", label: "43°" },
        { id: "b", label: "45°" },
        { id: "c", label: "39°" },
        { id: "d", label: "51°" },
      ],
      correct: "a",
      explain: "Angles on a straight line add to 180°: 3x + 51 = 180 → 3x = 129 → x = 43°.",
    },
    {
      type: "book-question",
      id: "bq-4",
      questionId: "pil-bq-4",
      eyebrow: "📖 Practice (from Example 8)",
      prompt: "Around a point, the angles are x, 3x, 2x, 10° and 4x. Find x.",
      options: [
        { id: "a", label: "36°" },
        { id: "b", label: "35°" },
        { id: "c", label: "40°" },
        { id: "d", label: "30°" },
      ],
      correct: "b",
      explain: "Angles round a point add to 360°: 10x + 10 = 360 → 10x = 350 → x = 35°.",
    },
    {
      type: "book-question",
      id: "bq-5",
      questionId: "pil-bq-5",
      eyebrow: "📖 Practice (from Example 5)",
      prompt: "Two complementary angles are in the ratio 7 : 8. The angles are…",
      options: [
        { id: "a", label: "42° and 48°" },
        { id: "b", label: "70° and 80°" },
        { id: "c", label: "35° and 55°" },
        { id: "d", label: "84° and 96°" },
      ],
      correct: "a",
      explain: "7x + 8x = 90 → 15x = 90 → x = 6 → the angles are 42° and 48°.",
    },
    {
      type: "concept",
      id: "transversal-intro",
      eyebrow: "🛣️ New Character",
      title: "The transversal",
      body: "A transversal is a line that cuts across two or more lines at distinct points — like a road crossing both railway tracks. One transversal crossing two lines creates EIGHT angles: four interior (between the lines) and four exterior (outside them). Hidden inside those eight angles are three secret letters…",
    },
    { type: "custom", id: "letter-hunt", component: "letter-hunt" },
    {
      type: "concept",
      id: "fzc-recap",
      eyebrow: "🔤 The Secret Code",
      title: "F · Z · C — the whole chapter in three letters",
      body: "When (and ONLY when) the lines are parallel, the transversal obeys the code. Tap each letter.",
      cards: [
        { icon: "🇫", front: "F = Corresponding", back: "Same position at each crossing → EQUAL. Trace an F on the figure and its two corners are the pair." },
        { icon: "🇿", front: "Z = Alternate", back: "Inside the parallels, opposite sides of the transversal → EQUAL. The Z's corners are the pair." },
        { icon: "🇨", front: "C = Co-interior", back: "Inside, same side of the transversal → ADD TO 180°. The C's corners are the pair." },
      ],
    },
    {
      type: "book-question",
      id: "bq-6",
      questionId: "pil-bq-6",
      eyebrow: "📖 Practice (from Example 9)",
      prompt: "AB ∥ CD and a transversal makes an angle of 70° with AB. The ALTERNATE angle x at CD equals…",
      options: [
        { id: "a", label: "70°" },
        { id: "b", label: "110°" },
        { id: "c", label: "20°" },
        { id: "d", label: "140°" },
      ],
      correct: "a",
      explain: "Alternate angles between parallel lines are equal — the Z rule. x = 70°.",
    },
    { type: "custom", id: "parallel-tester", component: "parallel-tester" },
    {
      type: "vocab",
      id: "keywords",
      eyebrow: "🔤 Engineer's Glossary",
      title: "Words to know",
      words: [
        { word: "Intersecting lines", meaning: "Lines that cross each other at exactly one point — the point of intersection." },
        { word: "Perpendicular lines", meaning: "Lines that intersect at right angles (90°). Symbol: ⊥." },
        { word: "Parallel lines", meaning: "Lines in a plane that never meet, staying the same distance apart. Symbol: ∥." },
        { word: "Transversal", meaning: "A line that cuts across two or more lines at distinct points." },
        { word: "Linear pair", meaning: "Two adjacent angles whose outer arms form a straight line — they add to 180°." },
        { word: "Vertically opposite angles", meaning: "Angles facing each other across a crossing — always equal." },
        { word: "Complementary angles", meaning: "Two angles whose sum is 90°." },
        { word: "Supplementary angles", meaning: "Two angles whose sum is 180°." },
        { word: "Corresponding angles", meaning: "Angles at the same position at each crossing of a transversal — the F pair. Equal when lines are parallel." },
        { word: "Alternate angles", meaning: "Interior angles on opposite sides of the transversal — the Z pair. Equal when lines are parallel." },
        { word: "Co-interior angles", meaning: "Interior angles on the same side of the transversal — the C pair. They add to 180° when lines are parallel." },
      ],
    },
    {
      type: "quiz",
      id: "boss-quiz",
      eyebrow: "🏆 Boss Quiz",
      title: "The Line City final inspection",
      questions: [
        {
          questionId: "pil-quiz-1",
          prompt: "The supplement of 120° is…",
          options: [
            { id: "a", label: "60°" },
            { id: "b", label: "80°" },
            { id: "c", label: "240°" },
            { id: "d", label: "30°" },
          ],
          correct: "a",
          explain: "Supplements add to 180°: 180° − 120° = 60°.",
        },
        {
          questionId: "pil-quiz-2",
          prompt: "Two lines cross. One angle is 40°. Its vertically opposite angle is…",
          options: [
            { id: "a", label: "140°" },
            { id: "b", label: "50°" },
            { id: "c", label: "40°" },
            { id: "d", label: "320°" },
          ],
          correct: "c",
          explain: "Vertically opposite angles are always equal — you saw it in the scissors!",
        },
        {
          questionId: "pil-quiz-3",
          prompt: "One angle of a linear pair is 110°. The other is…",
          options: [
            { id: "a", label: "110°" },
            { id: "b", label: "70°" },
            { id: "c", label: "250°" },
            { id: "d", label: "90°" },
          ],
          correct: "b",
          explain: "A linear pair adds to 180°: 180° − 110° = 70°.",
        },
        {
          questionId: "pil-quiz-4",
          prompt: "The sum of ALL the angles round a point is…",
          options: [
            { id: "a", label: "180°" },
            { id: "b", label: "90°" },
            { id: "c", label: "270°" },
            { id: "d", label: "360°" },
          ],
          correct: "d",
        },
        {
          questionId: "pil-quiz-5",
          prompt: "The hidden letter F on a transversal figure marks which pair?",
          options: [
            { id: "a", label: "Corresponding angles" },
            { id: "b", label: "Alternate angles" },
            { id: "c", label: "Co-interior angles" },
            { id: "d", label: "Vertically opposite angles" },
          ],
          correct: "a",
        },
        {
          questionId: "pil-quiz-6",
          prompt: "The Z pair (alternate angles) between parallel lines are always…",
          options: [
            { id: "a", label: "Supplementary" },
            { id: "b", label: "Equal" },
            { id: "c", label: "Complementary" },
            { id: "d", label: "90° each" },
          ],
          correct: "b",
        },
        {
          questionId: "pil-quiz-7",
          prompt: "Co-interior angles (the C pair) between parallel lines always…",
          options: [
            { id: "a", label: "Are equal" },
            { id: "b", label: "Add up to 90°" },
            { id: "c", label: "Add up to 180°" },
            { id: "d", label: "Add up to 360°" },
          ],
          correct: "c",
        },
        {
          questionId: "pil-quiz-8",
          prompt: "A transversal cuts two lines. Corresponding angles measure 85° and 80°. The lines are…",
          options: [
            { id: "a", label: "Parallel" },
            { id: "b", label: "Perpendicular" },
            { id: "c", label: "Not parallel" },
            { id: "d", label: "Overlapping" },
          ],
          correct: "c",
          explain: "For parallel lines corresponding angles must be EQUAL — 85° ≠ 80°, so not parallel.",
        },
      ],
    },
    {
      type: "concept",
      id: "done",
      eyebrow: "🎉 Chapter Complete",
      title: "Line City is safe in your hands",
      body: "You tuned every angle type, found the partners that make 90° and 180°, cracked the scissors code, hunted down every hidden F, Z and C, and judged lines like a true engineer — by their angles, never by their looks. The Golden Protractor is yours!",
    },
  ],
};
