import type { Chapter } from "../types";

// Class 7 Maths Ch. 5 (textbook pages 99–117) — built around "Line City":
// every crossing hides secrets (equal angles, hidden letters F/Z/C), and the
// student earns each rule by driving the simulations. Tracked ids pil-bq-* /
// pil-quiz-* are stable — never reuse for different questions.
export const parallelIntersectingLinesChapter: Chapter = {
  slug: "parallel-intersecting-lines",
  title: "Parallel and Intersecting Lines",
  subject: "Maths",
  emoji: "📐",
  color: "#6c63ff",
  description: "Spin angles, crack the scissors code, hunt the hidden letters F, Z and C, and judge which lines can never meet.",
  trophy: { emoji: "📐", name: "Golden Protractor", caption: "Hunted every hidden letter and judged every line in Line City." },
  scenes: [
    {
      type: "concept",
      id: "hook",
      eyebrow: "🏙️ Welcome to Line City",
      title: "Lines are running your life",
      body: "Railway tracks that never meet. Scissor blades that cross. The letter T in a signboard, standing perfectly upright. Every pair of lines in the world is playing by secret rules — and by the end of this chapter you'll know them all: which lines meet, which never can, and the hidden letters that reveal every angle's value.",
    },
    {
      type: "match",
      id: "spot-lines-match",
      eyebrow: "🎮 Spot the Pair",
      title: "What kind of line pair is it?",
      prompt: "Tap a real thing, then tap the kind of line pair it shows.",
      pairs: [
        { left: "Railway track", right: "Parallel lines" },
        { left: "Open scissor blades", right: "Intersecting lines" },
        { left: "The letter T", right: "Perpendicular lines" },
        { left: "Ruler's two long edges", right: "Parallel lines" },
        { left: "Two crossing roads", right: "Intersecting lines" },
        { left: "Flagstaff on the ground", right: "Perpendicular lines" },
      ],
    },
    {
      type: "concept",
      id: "pair-of-lines",
      eyebrow: "📖 The Three Pairs",
      title: "Intersecting, perpendicular, parallel",
      body: "Tap each card — and meet the two symbols mathematicians use.",
      cards: [
        { icon: "✂️", front: "Intersecting", back: "Cross each other at exactly one point — the point of intersection. Like scissor blades!" },
        { icon: "🚩", front: "Perpendicular", back: "Intersect at exactly 90°. Symbol: ⊥ (p ⊥ q). A square corner marks the right angle." },
        { icon: "🛤️", front: "Parallel", back: "Never meet, however far you extend them — always the same distance apart. Symbol: ∥ (p ∥ q)." },
      ],
    },
    { type: "custom", id: "angle-tuner", component: "angle-tuner" },
    {
      type: "sort",
      id: "angle-type-sort",
      eyebrow: "🗂️ Sort It",
      title: "Acute or obtuse?",
      prompt: "Less than 90° = acute. Between 90° and 180° = obtuse. Sort them!",
      buckets: ["Acute 🤏", "Obtuse 🦅"],
      items: [
        { label: "35°", bucket: 0 },
        { label: "120°", bucket: 1 },
        { label: "89°", bucket: 0 },
        { label: "91°", bucket: 1 },
        { label: "45°", bucket: 0 },
        { label: "175°", bucket: 1 },
      ],
    },
    { type: "custom", id: "angle-partners", component: "angle-partners" },
    {
      type: "book-question",
      id: "bq-1",
      questionId: "pil-bq-1",
      eyebrow: "📖 Practice",
      prompt: "The complement of 35° is…",
      options: [
        { id: "a", label: "55°" },
        { id: "b", label: "65°" },
        { id: "c", label: "145°" },
        { id: "d", label: "45°" },
      ],
      correct: "a",
      explain: "Complements add to 90°: 90° − 35° = 55°.",
    },
    {
      type: "book-question",
      id: "bq-2",
      questionId: "pil-bq-2",
      eyebrow: "📖 Practice (algebra!)",
      prompt: "∠A and ∠B are complementary. If ∠A = (7 + 4x)° and ∠B = (x + 23)°, find x.",
      options: [
        { id: "a", label: "x = 8" },
        { id: "b", label: "x = 10" },
        { id: "c", label: "x = 12" },
        { id: "d", label: "x = 15" },
      ],
      correct: "c",
      explain: "7 + 4x + x + 23 = 90 → 5x + 30 = 90 → 5x = 60 → x = 12.",
    },
    { type: "custom", id: "scissors-sim", component: "scissors-sim" },
    {
      type: "concept",
      id: "angle-pairs",
      eyebrow: "📖 Naming What You Found",
      title: "The angle pairs of every crossing",
      body: "The scissors showed you the rules — here are their official names. Tap each card.",
      cards: [
        { icon: "🤝", front: "Adjacent angles", back: "Share a vertex and a common arm, with no overlap — they sit 'next to' each other." },
        { icon: "📏", front: "Linear pair", back: "Adjacent angles whose outer arms form a straight line. Always add to 180°." },
        { icon: "❌", front: "Vertically opposite", back: "The angles facing each other across a crossing. Always EQUAL." },
        { icon: "🎡", front: "Angles at a point", back: "All the angles around one point always add to 360° — one full rotation." },
      ],
    },
    {
      type: "book-question",
      id: "bq-3",
      questionId: "pil-bq-3",
      eyebrow: "📖 Practice (from Example 7)",
      prompt: "Three angles on a straight line measure (x + 31)°, (x + 20)° and x°. Find x.",
      options: [
        { id: "a", label: "43°" },
        { id: "b", label: "45°" },
        { id: "c", label: "39°" },
        { id: "d", label: "51°" },
      ],
      correct: "a",
      explain: "Angles on a straight line add to 180°: 3x + 51 = 180 → 3x = 129 → x = 43°.",
    },
    {
      type: "book-question",
      id: "bq-4",
      questionId: "pil-bq-4",
      eyebrow: "📖 Practice (from Example 8)",
      prompt: "Around a point, the angles are x, 3x, 2x, 10° and 4x. Find x.",
      options: [
        { id: "a", label: "36°" },
        { id: "b", label: "35°" },
        { id: "c", label: "40°" },
        { id: "d", label: "30°" },
      ],
      correct: "b",
      explain: "Angles round a point add to 360°: 10x + 10 = 360 → 10x = 350 → x = 35°.",
    },
    {
      type: "book-question",
      id: "bq-5",
      questionId: "pil-bq-5",
      eyebrow: "📖 Practice (from Example 5)",
      prompt: "Two complementary angles are in the ratio 7 : 8. The angles are…",
      options: [
        { id: "a", label: "42° and 48°" },
        { id: "b", label: "70° and 80°" },
        { id: "c", label: "35° and 55°" },
        { id: "d", label: "84° and 96°" },
      ],
      correct: "a",
      explain: "7x + 8x = 90 → 15x = 90 → x = 6 → the angles are 42° and 48°.",
    },
    {
      type: "concept",
      id: "transversal-intro",
      eyebrow: "🛣️ New Character",
      title: "The transversal",
      body: "A transversal is a line that cuts across two or more lines at distinct points — like a road crossing both railway tracks. One transversal crossing two lines creates EIGHT angles: four interior (between the lines) and four exterior (outside them). Hidden inside those eight angles are three secret letters…",
    },
    { type: "custom", id: "letter-hunt", component: "letter-hunt" },
    {
      type: "concept",
      id: "fzc-recap",
      eyebrow: "🔤 The Secret Code",
      title: "F · Z · C — the whole chapter in three letters",
      body: "When (and ONLY when) the lines are parallel, the transversal obeys the code. Tap each letter.",
      cards: [
        { icon: "🇫", front: "F = Corresponding", back: "Same position at each crossing → EQUAL. Trace an F on the figure and its two corners are the pair." },
        { icon: "🇿", front: "Z = Alternate", back: "Inside the parallels, opposite sides of the transversal → EQUAL. The Z's corners are the pair." },
        { icon: "🇨", front: "C = Co-interior", back: "Inside, same side of the transversal → ADD TO 180°. The C's corners are the pair." },
      ],
    },
    {
      type: "book-question",
      id: "bq-6",
      questionId: "pil-bq-6",
      eyebrow: "📖 Practice (from Example 9)",
      prompt: "AB ∥ CD and a transversal makes an angle of 70° with AB. The ALTERNATE angle x at CD equals…",
      options: [
        { id: "a", label: "70°" },
        { id: "b", label: "110°" },
        { id: "c", label: "20°" },
        { id: "d", label: "140°" },
      ],
      correct: "a",
      explain: "Alternate angles between parallel lines are equal — the Z rule. x = 70°.",
    },
    { type: "custom", id: "parallel-tester", component: "parallel-tester" },
    {
      type: "vocab",
      id: "keywords",
      eyebrow: "🔤 Engineer's Glossary",
      title: "Words to know",
      words: [
        { word: "Intersecting lines", meaning: "Lines that cross each other at exactly one point — the point of intersection." },
        { word: "Perpendicular lines", meaning: "Lines that intersect at right angles (90°). Symbol: ⊥." },
        { word: "Parallel lines", meaning: "Lines in a plane that never meet, staying the same distance apart. Symbol: ∥." },
        { word: "Transversal", meaning: "A line that cuts across two or more lines at distinct points." },
        { word: "Linear pair", meaning: "Two adjacent angles whose outer arms form a straight line — they add to 180°." },
        { word: "Vertically opposite angles", meaning: "Angles facing each other across a crossing — always equal." },
        { word: "Complementary angles", meaning: "Two angles whose sum is 90°." },
        { word: "Supplementary angles", meaning: "Two angles whose sum is 180°." },
        { word: "Corresponding angles", meaning: "Angles at the same position at each crossing of a transversal — the F pair. Equal when lines are parallel." },
        { word: "Alternate angles", meaning: "Interior angles on opposite sides of the transversal — the Z pair. Equal when lines are parallel." },
        { word: "Co-interior angles", meaning: "Interior angles on the same side of the transversal — the C pair. They add to 180° when lines are parallel." },
      ],
    },
    {
      type: "quiz",
      id: "boss-quiz",
      eyebrow: "🏆 Boss Quiz",
      title: "The Line City final inspection",
      questions: [
        {
          questionId: "pil-quiz-1",
          prompt: "The supplement of 120° is…",
          options: [
            { id: "a", label: "60°" },
            { id: "b", label: "80°" },
            { id: "c", label: "240°" },
            { id: "d", label: "30°" },
          ],
          correct: "a",
          explain: "Supplements add to 180°: 180° − 120° = 60°.",
        },
        {
          questionId: "pil-quiz-2",
          prompt: "Two lines cross. One angle is 40°. Its vertically opposite angle is…",
          options: [
            { id: "a", label: "140°" },
            { id: "b", label: "50°" },
            { id: "c", label: "40°" },
            { id: "d", label: "320°" },
          ],
          correct: "c",
          explain: "Vertically opposite angles are always equal — you saw it in the scissors!",
        },
        {
          questionId: "pil-quiz-3",
          prompt: "One angle of a linear pair is 110°. The other is…",
          options: [
            { id: "a", label: "110°" },
            { id: "b", label: "70°" },
            { id: "c", label: "250°" },
            { id: "d", label: "90°" },
          ],
          correct: "b",
          explain: "A linear pair adds to 180°: 180° − 110° = 70°.",
        },
        {
          questionId: "pil-quiz-4",
          prompt: "The sum of ALL the angles round a point is…",
          options: [
            { id: "a", label: "180°" },
            { id: "b", label: "90°" },
            { id: "c", label: "270°" },
            { id: "d", label: "360°" },
          ],
          correct: "d",
        },
        {
          questionId: "pil-quiz-5",
          prompt: "The hidden letter F on a transversal figure marks which pair?",
          options: [
            { id: "a", label: "Corresponding angles" },
            { id: "b", label: "Alternate angles" },
            { id: "c", label: "Co-interior angles" },
            { id: "d", label: "Vertically opposite angles" },
          ],
          correct: "a",
        },
        {
          questionId: "pil-quiz-6",
          prompt: "The Z pair (alternate angles) between parallel lines are always…",
          options: [
            { id: "a", label: "Supplementary" },
            { id: "b", label: "Equal" },
            { id: "c", label: "Complementary" },
            { id: "d", label: "90° each" },
          ],
          correct: "b",
        },
        {
          questionId: "pil-quiz-7",
          prompt: "Co-interior angles (the C pair) between parallel lines always…",
          options: [
            { id: "a", label: "Are equal" },
            { id: "b", label: "Add up to 90°" },
            { id: "c", label: "Add up to 180°" },
            { id: "d", label: "Add up to 360°" },
          ],
          correct: "c",
        },
        {
          questionId: "pil-quiz-8",
          prompt: "A transversal cuts two lines. Corresponding angles measure 85° and 80°. The lines are…",
          options: [
            { id: "a", label: "Parallel" },
            { id: "b", label: "Perpendicular" },
            { id: "c", label: "Not parallel" },
            { id: "d", label: "Overlapping" },
          ],
          correct: "c",
          explain: "For parallel lines corresponding angles must be EQUAL — 85° ≠ 80°, so not parallel.",
        },
      ],
    },
    {
      type: "concept",
      id: "exercise-pointer",
      eyebrow: "📚 Homework Zone",
      title: "The full exercises are waiting",
      body: "Every question from Exercise 5A and 5B — with figures — lives in your Practice Arena under this chapter. That's where homework happens: pick this chapter, choose your questions, and every answer counts towards your XP, streak and Today's Review.",
    },
    {
      type: "concept",
      id: "done",
      eyebrow: "🎉 Chapter Complete",
      title: "Line City is safe in your hands",
      body: "You tuned every angle type, found the partners that make 90° and 180°, cracked the scissors code, hunted down every hidden F, Z and C, and judged lines like a true engineer — by their angles, never by their looks. The Golden Protractor is yours!",
    },
  ],
  exercises: [
    // ——— Exercise 5A ———
    {
      questionId: "pil-ex-a1",
      prompt: "Two complementary angles differ by 30°. The angles are…",
      options: [
        { id: "a", label: "30° and 60°" },
        { id: "b", label: "45° and 75°" },
        { id: "c", label: "60° and 90°" },
        { id: "d", label: "25° and 55°" },
      ],
      correct: "a",
      explain: "x + (x + 30) = 90 → 2x = 60 → x = 30. The angles are 30° and 60°.",
    },
    {
      questionId: "pil-ex-a2",
      prompt: "Two complementary angles: the larger is 5 times the smaller. The angles are…",
      options: [
        { id: "a", label: "18° and 90°" },
        { id: "b", label: "15° and 75°" },
        { id: "c", label: "20° and 100°" },
        { id: "d", label: "10° and 50°" },
      ],
      correct: "b",
      explain: "x + 5x = 90 → 6x = 90 → x = 15. The angles are 15° and 75°.",
    },
    {
      questionId: "pil-ex-a3",
      prompt: "Two supplementary angles: the smaller is one-fourth of the larger. The angles are…",
      options: [
        { id: "a", label: "45° and 135°" },
        { id: "b", label: "30° and 150°" },
        { id: "c", label: "36° and 144°" },
        { id: "d", label: "40° and 160°" },
      ],
      correct: "c",
      explain: "L/4 + L = 180 → 5L/4 = 180 → L = 144, and 144 ÷ 4 = 36.",
    },
    {
      questionId: "pil-ex-a4",
      prompt: "Two angles are vertically opposite AND complementary. Each angle measures…",
      options: [
        { id: "a", label: "90°" },
        { id: "b", label: "60°" },
        { id: "c", label: "30°" },
        { id: "d", label: "45°" },
      ],
      correct: "d",
      explain: "Vertically opposite → equal; complementary → sum 90°. So x + x = 90 → x = 45°.",
    },
    {
      questionId: "pil-ex-a5",
      prompt: "The complement of 61° is…",
      options: [
        { id: "a", label: "29°" },
        { id: "b", label: "39°" },
        { id: "c", label: "119°" },
        { id: "d", label: "31°" },
      ],
      correct: "a",
      explain: "90° − 61° = 29°.",
    },
    {
      questionId: "pil-ex-a6",
      prompt: "The supplement of 86° is…",
      options: [
        { id: "a", label: "4°" },
        { id: "b", label: "94°" },
        { id: "c", label: "104°" },
        { id: "d", label: "84°" },
      ],
      correct: "b",
      explain: "180° − 86° = 94°.",
    },
    {
      questionId: "pil-ex-a7",
      prompt: "Lines AB and CD intersect at O. The bottom angle is 36°. Find x.",
      figure: { kind: "crossing", labels: { b: "x", d: "36°" } },
      options: [
        { id: "a", label: "36°" },
        { id: "b", label: "144°" },
        { id: "c", label: "54°" },
        { id: "d", label: "72°" },
      ],
      correct: "a",
      explain: "x is vertically opposite the 36° angle — vertically opposite angles are equal.",
    },
    {
      questionId: "pil-ex-a8",
      prompt: "Same crossing: the bottom angle is 36°. Find y.",
      figure: { kind: "crossing", labels: { a: "y", d: "36°" } },
      options: [
        { id: "a", label: "36°" },
        { id: "b", label: "324°" },
        { id: "c", label: "144°" },
        { id: "d", label: "64°" },
      ],
      correct: "c",
      explain: "y and 36° form a linear pair on a straight line: y = 180° − 36° = 144°.",
    },
    {
      questionId: "pil-ex-a9",
      prompt: "Two lines intersect at O, and ∠AOC + ∠BOD = 266°. (∠AOC and ∠BOD are vertically opposite.) Each of them equals…",
      options: [
        { id: "a", label: "133°" },
        { id: "b", label: "94°" },
        { id: "c", label: "113°" },
        { id: "d", label: "66.5°" },
      ],
      correct: "a",
      explain: "Vertically opposite angles are equal, so each is 266° ÷ 2 = 133°.",
    },
    {
      questionId: "pil-ex-a10",
      prompt: "Two lines intersect at O, and ∠AOC + ∠BOC + ∠BOD = 338°. Find ∠BOD.",
      options: [
        { id: "a", label: "113°" },
        { id: "b", label: "158°" },
        { id: "c", label: "180°" },
        { id: "d", label: "22°" },
      ],
      correct: "b",
      explain: "∠AOC + ∠BOC = 180° (linear pair), so ∠BOD = 338° − 180° = 158°.",
    },
    {
      questionId: "pil-ex-a11",
      prompt: "AD bisects ∠CAB. If ∠CAD = (8x + 6)° and ∠DAB = (x + 20)°, find x.",
      options: [
        { id: "a", label: "x = 4" },
        { id: "b", label: "x = 3" },
        { id: "c", label: "x = 2" },
        { id: "d", label: "x = 7" },
      ],
      correct: "c",
      explain: "A bisector makes the two parts EQUAL: 8x + 6 = x + 20 → 7x = 14 → x = 2.",
    },
    {
      questionId: "pil-ex-a12",
      prompt: "∠1 and ∠2 are complementary; ∠2 and ∠3 are supplementary. If ∠1 = 45°, find ∠3.",
      options: [
        { id: "a", label: "45°" },
        { id: "b", label: "90°" },
        { id: "c", label: "120°" },
        { id: "d", label: "135°" },
      ],
      correct: "d",
      explain: "∠2 = 90° − 45° = 45°, then ∠3 = 180° − 45° = 135°.",
    },
    // ——— Exercise 5B ———
    {
      questionId: "pil-ex-b1",
      prompt: "l ∥ m. Find a.",
      figure: { kind: "transversal", labels: { "4": "70°", "6": "a" } },
      options: [
        { id: "a", label: "70°" },
        { id: "b", label: "110°" },
        { id: "c", label: "20°" },
        { id: "d", label: "140°" },
      ],
      correct: "a",
      explain: "∠4 and ∠6 are alternate angles (the Z pair) — equal when lines are parallel.",
    },
    {
      questionId: "pil-ex-b2",
      prompt: "l ∥ m. Find x.",
      figure: { kind: "transversal", labels: { "3": "105°", "5": "x" } },
      options: [
        { id: "a", label: "75°" },
        { id: "b", label: "105°" },
        { id: "c", label: "115°" },
        { id: "d", label: "95°" },
      ],
      correct: "b",
      explain: "∠3 and ∠5 are alternate angles — equal. x = 105°.",
    },
    {
      questionId: "pil-ex-b3",
      prompt: "l ∥ m. Find a.",
      figure: { kind: "transversal", labels: { "2": "120°", "6": "a" } },
      options: [
        { id: "a", label: "60°" },
        { id: "b", label: "90°" },
        { id: "c", label: "120°" },
        { id: "d", label: "150°" },
      ],
      correct: "c",
      explain: "∠2 and ∠6 are corresponding angles (the F pair) — equal when lines are parallel.",
    },
    {
      questionId: "pil-ex-b4",
      prompt: "l ∥ m. Find x.",
      figure: { kind: "transversal", labels: { "1": "130°", "5": "x" } },
      options: [
        { id: "a", label: "50°" },
        { id: "b", label: "65°" },
        { id: "c", label: "115°" },
        { id: "d", label: "130°" },
      ],
      correct: "d",
      explain: "∠1 and ∠5 are corresponding angles — equal. x = 130°.",
    },
    {
      questionId: "pil-ex-b5",
      prompt: "l ∥ m. Find x.",
      figure: { kind: "transversal", labels: { "3": "120°", "6": "x" } },
      options: [
        { id: "a", label: "60°" },
        { id: "b", label: "120°" },
        { id: "c", label: "90°" },
        { id: "d", label: "80°" },
      ],
      correct: "a",
      explain: "∠3 and ∠6 are co-interior (the C pair) — they add to 180°. x = 180° − 120° = 60°.",
    },
    {
      questionId: "pil-ex-b6",
      prompt: "l ∥ m. Find x.",
      figure: { kind: "transversal", labels: { "4": "105°", "5": "x" } },
      options: [
        { id: "a", label: "105°" },
        { id: "b", label: "85°" },
        { id: "c", label: "65°" },
        { id: "d", label: "75°" },
      ],
      correct: "d",
      explain: "∠4 and ∠5 are co-interior — sum 180°. x = 180° − 105° = 75°.",
    },
    {
      questionId: "pil-ex-b7",
      prompt: "A transversal makes corresponding angles ∠a = 85° and ∠b = 85° with lines AB and CD. Are the lines parallel?",
      options: [
        { id: "a", label: "Yes — corresponding angles are equal" },
        { id: "b", label: "No — the angles should add to 180°" },
        { id: "c", label: "No — corresponding angles must be 90°" },
        { id: "d", label: "Can't say without measuring the lines" },
      ],
      correct: "a",
      explain: "Equal corresponding angles is exactly the test: AB ∥ CD.",
    },
    {
      questionId: "pil-ex-b8",
      prompt: "A transversal makes alternate angles ∠b = 89° and ∠c = 89° with lines EF and GH. Are the lines parallel?",
      options: [
        { id: "a", label: "No — 89° is not 90°" },
        { id: "b", label: "Yes — alternate angles are equal" },
        { id: "c", label: "No — they must add to 180°" },
        { id: "d", label: "Only if the transversal is perpendicular" },
      ],
      correct: "b",
      explain: "Equal alternate angles → EF ∥ GH. (They don't need to be 90° — just equal!)",
    },
    {
      questionId: "pil-ex-b9",
      prompt: "A transversal makes co-interior angles of 112° and 68° with two lines. Are the lines parallel?",
      options: [
        { id: "a", label: "No — the angles are not equal" },
        { id: "b", label: "Yes — 112° + 68° = 180°" },
        { id: "c", label: "No — 112° + 68° ≠ 90°" },
        { id: "d", label: "Can't say" },
      ],
      correct: "b",
      explain: "Co-interior angles adding to exactly 180° is the test — the lines are parallel.",
    },
    {
      questionId: "pil-ex-b10",
      prompt: "AB ∥ CD. Two co-interior angles measure x and 3x. Find x.",
      figure: { kind: "transversal", labels: { "4": "x", "5": "3x" } },
      options: [
        { id: "a", label: "30°" },
        { id: "b", label: "60°" },
        { id: "c", label: "45°" },
        { id: "d", label: "36°" },
      ],
      correct: "c",
      explain: "Co-interior angles add to 180°: x + 3x = 180 → 4x = 180 → x = 45°.",
    },
    {
      questionId: "pil-ex-b11",
      prompt: "PQ ∥ RS. A corresponding pair measures (3x − 15)° and 90°. Find x.",
      options: [
        { id: "a", label: "x = 25" },
        { id: "b", label: "x = 30" },
        { id: "c", label: "x = 35" },
        { id: "d", label: "x = 45" },
      ],
      correct: "c",
      explain: "Corresponding angles are equal: 3x − 15 = 90 → 3x = 105 → x = 35.",
    },
    {
      questionId: "pil-ex-b12",
      prompt: "l ∥ m. Find x.",
      figure: { kind: "transversal", labels: { "2": "115°", "6": "x" } },
      options: [
        { id: "a", label: "115°" },
        { id: "b", label: "65°" },
        { id: "c", label: "75°" },
        { id: "d", label: "180°" },
      ],
      correct: "a",
      explain: "∠2 and ∠6 are corresponding angles — equal. x = 115°.",
    },
    {
      questionId: "pil-ex-b13",
      prompt: "Around a point, three angles measure 270°, 42° and q. Find q.",
      options: [
        { id: "a", label: "48°" },
        { id: "b", label: "58°" },
        { id: "c", label: "42°" },
        { id: "d", label: "90°" },
      ],
      correct: "a",
      explain: "Angles round a point add to 360°: q = 360° − 270° − 42° = 48°.",
    },
    // ——— True / False ———
    {
      questionId: "pil-tf-1",
      prompt: "True or False: Vertically opposite angles are always equal.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    {
      questionId: "pil-tf-2",
      prompt: "True or False: The sum of the angles on a straight line is 360°.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "b",
      explain: "Angles on a straight line add up to 180°. A full turn round a point is 360°.",
    },
    {
      questionId: "pil-tf-3",
      prompt: "True or False: Two lines in a plane that never meet are called parallel lines.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    {
      questionId: "pil-tf-4",
      prompt: "True or False: Co-interior angles between parallel lines are equal.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "b",
      explain: "Co-interior (C) angles are supplementary — they add up to 180°, not equal.",
    },
    // ——— Fill in the blanks ———
    {
      questionId: "pil-fb-1",
      prompt: "Two angles whose sum is 90° are called ______ angles.",
      qtype: "fill-blank",
      answers: ["complementary"],
    },
    {
      questionId: "pil-fb-2",
      prompt: "Two angles whose sum is 180° are called ______ angles.",
      qtype: "fill-blank",
      answers: ["supplementary"],
    },
    {
      questionId: "pil-fb-3",
      prompt: "The sum of all the angles around a point is ______ degrees.",
      qtype: "fill-blank",
      answers: ["360", "360°"],
    },
    {
      questionId: "pil-fb-4",
      prompt: "The complement of a 60° angle is ______ degrees.",
      qtype: "fill-blank",
      answers: ["30", "30°"],
    },
  ],
};
