import type { Chapter } from "../types";

// NCERT Class 7 Science Ch. 5 — built around "The Undo Button": which changes
// will the universe let you reverse, and which ones make something NEW?
// Tracked ids (pcc-bq-*, pcc-quiz-*) are stable — never reuse for different
// questions.
export const physicalChemicalChangesChapter: Chapter = {
  slug: "physical-chemical-changes",
  title: "Physical and Chemical Changes",
  subject: "Science",
  emoji: "🔄",
  color: "#1db88a",
  description: "Press the universe's UNDO button, grow crystals, race rust, and learn which changes can never go back.",
  trophy: { emoji: "🛡️", name: "Rust-Proof Shield", caption: "Proved what rust needs, stopped it cold, and mastered every change." },
  scenes: [
    {
      type: "concept",
      id: "hook",
      eyebrow: "🕹️ The Big Question",
      title: "What if the world had an UNDO button?",
      body: "You press Ctrl+Z and your typing mistake vanishes. But can you un-melt an ice cream? Un-burn a matchstick? Un-ripen a banana? Changes are happening all around us — even inside us — and today you get a magical UNDO button to test them. Let's see when the universe says YES… and when it flatly refuses.",
    },
    { type: "custom", id: "undo-lab", component: "undo-lab" },
    {
      type: "concept",
      id: "reversible-irreversible",
      eyebrow: "📖 Naming What You Found",
      title: "Reversible and irreversible changes",
      body: "A change that can happen backwards is reversible (water ↔ ice). One that can't be undone is irreversible (a tree growing taller). Two more things you discovered: changes never happen on their own — there is always a CAUSE (ice needs heat to melt). And changes can be helpful or harmful — tap the cards.",
      cards: [
        { icon: "🍌", front: "Helpful change", back: "Ripening of fruits — we even speed it up artificially!" },
        { icon: "🟤", front: "Harmful change", back: "Rusting of iron — we spend crores fighting it." },
        { icon: "⚡", front: "Every change has a cause", back: "Ice doesn't melt on its own — HEAT is the cause. No cause, no change." },
      ],
    },
    { type: "custom", id: "heat-lab", component: "heat-lab" },
    {
      type: "concept",
      id: "physical-defined",
      eyebrow: "🧊 Family #1",
      title: "Physical changes: same substance, new look",
      body: "When only physical properties change — state, size, shape, colour — and NO new substance forms, it's a physical change. They're usually temporary, often reversible, and involve very little energy. Tap the classic examples.",
      cards: [
        { icon: "✂️", front: "Cutting paper", back: "Pieces can't rejoin, but every piece is still paper. Physical — and a reminder that physical changes may or may not be reversible!" },
        { icon: "🖍️", front: "Chalk → chalk dust", back: "Same substance, smaller size. Chalk dust can even be pressed back into sticks." },
        { icon: "🥛", front: "Breaking a glass", back: "Every sharp piece is still glass — only size and shape changed." },
        { icon: "♨️", front: "Boiling & condensing", back: "Water → steam → water: state changes only, same H₂O molecules throughout." },
      ],
    },
    {
      type: "sort",
      id: "reversible-sort",
      eyebrow: "🎮 Sort It",
      title: "Can the universe undo it?",
      prompt: "Sort each change: reversible or irreversible?",
      buckets: ["Reversible ⟲", "Irreversible 🚫"],
      items: [
        { label: "Ice melting", bucket: 0 },
        { label: "A tree growing taller", bucket: 1 },
        { label: "Water boiling to steam", bucket: 0 },
        { label: "Milk turning to curd", bucket: 1 },
        { label: "Freezing water to ice", bucket: 0 },
        { label: "A fruit ripening", bucket: 1 },
      ],
    },
    {
      type: "book-question",
      id: "bq-1",
      questionId: "pcc-bq-1",
      eyebrow: "📖 Practice",
      prompt: "Which of the following is NOT a physical change?",
      options: [
        { id: "a", label: "Salt is added to water" },
        { id: "b", label: "Charcoal burns" },
        { id: "c", label: "Ice melts" },
        { id: "d", label: "An iron nail is magnetised" },
      ],
      correct: "b",
      explain: "Burning always creates new substances (gases, ash) — that makes it a chemical change.",
    },
    {
      type: "concept",
      id: "chemical-defined",
      eyebrow: "🔥 Family #2",
      title: "Chemical changes: something NEW is born",
      body: "When a change creates a brand-new substance with completely different properties, it's a chemical change (also called a chemical reaction). These are usually permanent — no undo! — and a LOT of energy (heat, light, sound) is absorbed or released. Time to see the tell-tale signs with your own eyes…",
    },
    { type: "custom", id: "reaction-lab", component: "reaction-lab" },
    {
      type: "book-question",
      id: "bq-2",
      questionId: "pcc-bq-2",
      eyebrow: "📖 Practice",
      prompt: "The gas that turns lime water milky is…",
      options: [
        { id: "a", label: "Sulphur dioxide" },
        { id: "b", label: "Nitrogen dioxide" },
        { id: "c", label: "Hydrogen chloride" },
        { id: "d", label: "Carbon dioxide" },
      ],
      correct: "d",
      explain: "CO₂ + lime water → calcium carbonate (the milkiness) + water. You performed this test in the Reaction Lab!",
    },
    {
      type: "concept",
      id: "chemical-everywhere",
      eyebrow: "🌍 Chemical Changes Everywhere",
      title: "Fire, food and fuel",
      body: "Chemical changes power the world around you. Tap each card.",
      cards: [
        { icon: "📄", front: "Burning paper", back: "Makes CO₂, water vapour, smoke and ash — plus heat and light. Can never become paper again." },
        { icon: "🍛", front: "Food spoiling", back: "That foul smell IS the evidence: new (smelly) substances have formed." },
        { icon: "🎆", front: "Fireworks exploding", back: "New substances + heat + light + sound — and sadly, polluting gases too." },
        { icon: "🐄", front: "Biogas", back: "Bacteria digest cow dung into methane (a chemical change) — and burning that methane for cooking is another one!" },
      ],
    },
    { type: "custom", id: "rust-lab", component: "rust-lab" },
    {
      type: "match",
      id: "rust-protection-match",
      eyebrow: "🛡️ Rust Defence Squad",
      title: "Match each protection to how it works",
      prompt: "All of them do one job: keep air and water away from the iron. Match!",
      pairs: [
        { left: "Painting", right: "Coat on gates, grills & bridges" },
        { left: "Grease or oil", right: "Smeared on tools & machine parts" },
        { left: "Galvanisation", right: "Thin zinc coating (dipped in molten zinc)" },
        { left: "Stainless steel", right: "Iron alloyed with carbon, chromium & nickel" },
      ],
    },
    {
      type: "concept",
      id: "iron-pillar",
      eyebrow: "🏛️ Wonder of India",
      title: "The pillar that refuses to rust",
      body: "Near the Qutub Minar in Delhi stands an iron pillar — over 7 metres tall, more than 6000 kg, built over 1600 years ago. It has barely rusted AT ALL. Indian metal-makers achieved rust resistance sixteen centuries ago that engineers still admire today. 🇮🇳",
    },
    {
      type: "book-question",
      id: "bq-3",
      questionId: "pcc-bq-3",
      eyebrow: "📖 Practice",
      prompt: "Which of the following is NOT a required condition for rusting to occur?",
      options: [
        { id: "a", label: "Presence of oxygen" },
        { id: "b", label: "Presence of CO₂" },
        { id: "c", label: "Presence of water vapour" },
        { id: "d", label: "Presence of water" },
      ],
      correct: "b",
      explain: "Your three test tubes proved it: rust needs air (oxygen) and water — CO₂ has nothing to do with it.",
    },
    {
      type: "custom",
      id: "mission-bicycle",
      component: "rescue-mission",
      props: {
        emoji: "🚲",
        title: "Riya's rain-soaked bicycle",
        situation: "Riya's new bicycle stands outside through the monsoon. Brown flaky spots are already spreading on the handlebar and chain!",
        question: "What should she do to save it?",
        choices: [
          { id: "a", label: "Wash it with water every day 🚿", outcome: "Worse! Water is one of the two things rust NEEDS. The rust spreads faster." },
          { id: "b", label: "Paint the frame and oil the chain 🎨🛢️", correct: true, outcome: "The paint and oil seal out air and water — the rust stops spreading." },
          { id: "c", label: "Cover it with a wet cloth 🧺", outcome: "You just wrapped it in the enemy — moisture held against the metal all day!" },
        ],
        explain: "Every rust defence works the same way: block air and water from touching the iron. Paint for frames, grease/oil for moving parts.",
      },
    },
    {
      type: "custom",
      id: "mission-apple",
      component: "rescue-mission",
      props: {
        emoji: "🍎",
        title: "The brown apple problem",
        situation: "Mum cuts apples for your tiffin at 7 am. By lunchtime they've turned an ugly brown — chemicals in the apple react with oxygen in the air to form a brown pigment called melanin.",
        question: "How do you keep the slices fresh-looking?",
        choices: [
          { id: "a", label: "Keep them in the open air to 'breathe' 🌬️", outcome: "More air = more oxygen = MORE browning. Fully brown by 9 am!" },
          { id: "b", label: "Soak the slices in water 💧", correct: true, outcome: "Lunchtime: the slices still look fresh!" },
          { id: "c", label: "Leave them in sunlight to dry 🌞", outcome: "Dry, warm and oxygen-rich — the browning goes even faster." },
        ],
        explain: "The water layer blocks atmospheric oxygen from reaching the fruit, so the browning reaction can't happen.",
      },
    },
    {
      type: "book-question",
      id: "bq-4",
      questionId: "pcc-bq-4",
      eyebrow: "📖 Practice",
      prompt: "Impure copper sulphate powder can be purified by the process of…",
      options: [
        { id: "a", label: "Galvanisation" },
        { id: "b", label: "Crystallisation" },
        { id: "c", label: "Sublimation" },
        { id: "d", label: "Evaporation" },
      ],
      correct: "b",
      explain: "Crystallisation grows large, pure crystals — the impurities stay behind in the solution.",
    },
    { type: "custom", id: "crystal-lab", component: "crystal-lab" },
    {
      type: "sort",
      id: "classify-sort",
      eyebrow: "🏆 The Great Classification",
      title: "Physical or chemical?",
      prompt: "The ultimate test from your book — sort every change into its family.",
      buckets: ["Physical 🧊", "Chemical 🔥"],
      items: [
        { label: "Souring of milk", bucket: 1 },
        { label: "Melting of wax", bucket: 0 },
        { label: "Digestion of food", bucket: 1 },
        { label: "Tearing of paper", bucket: 0 },
        { label: "Rusting of iron", bucket: 1 },
        { label: "Crystallisation of copper sulphate", bucket: 0 },
        { label: "Burning of wax", bucket: 1 },
        { label: "Condensation of water vapour", bucket: 0 },
        { label: "Browning of cut fruits", bucket: 1 },
      ],
    },
    {
      type: "vocab",
      id: "keywords",
      eyebrow: "🔤 Scientist's Glossary",
      title: "Words to know",
      words: [
        { word: "Physical change", meaning: "A change in physical properties — texture, shape, temperature, state — with no new substance formed." },
        { word: "Chemical change", meaning: "A change in chemical properties where a completely new substance is formed." },
        { word: "Chemical reaction", meaning: "The process in which substances undergo a chemical change to produce new substances with new properties." },
        { word: "Rusting", meaning: "Iron + oxygen + water forming a mixture of iron oxides (rust) on iron surfaces." },
        { word: "Galvanisation", meaning: "Coating iron or steel with a protective zinc layer to prevent rusting." },
        { word: "Crystal", meaning: "A solid particle with flat surfaces, straight edges and a regular shape." },
        { word: "Crystallisation", meaning: "The process of forming solid crystals from a solution — used to purify substances." },
      ],
    },
    {
      type: "book-question",
      id: "bq-5",
      questionId: "pcc-bq-5",
      eyebrow: "📖 Assertion & Reason",
      prompt: "Assertion (A): Sharpening a pencil is a physical change, although it cannot be reversed.\nReason (R): A chemical change involves a change in chemical properties or composition, forming a new substance.",
      options: [
        { id: "a", label: "Both A and R are true, and R correctly explains A" },
        { id: "b", label: "Both A and R are true, but R does not explain A" },
        { id: "c", label: "A is true, but R is false" },
        { id: "d", label: "A is false, but R is true" },
      ],
      correct: "b",
      explain: "Both statements are true — but R defines chemical change; it doesn't explain why sharpening is physical (that's because the shavings are still wood and graphite, like your cut paper!).",
    },
    {
      type: "book-question",
      id: "bq-6",
      questionId: "pcc-bq-6",
      eyebrow: "🧠 HOTS Riddle",
      prompt: "Substance A relieves ant stings AND is used in the kitchen. Substance B is sour, used in pickles, and contains organic acid C. Mixing A with B causes change D, releasing gas E.\nWhat are A, C and E?",
      options: [
        { id: "a", label: "A = baking soda, C = acetic acid, E = carbon dioxide" },
        { id: "b", label: "A = washing soda, C = citric acid, E = oxygen" },
        { id: "c", label: "A = common salt, C = formic acid, E = hydrogen" },
        { id: "d", label: "A = baking soda, C = lactic acid, E = carbon dioxide" },
      ],
      correct: "a",
      explain: "Baking soda (A) + vinegar (B, containing acetic acid C) → a chemical change (D) that fizzes out carbon dioxide (E). You did this one in the Reaction Lab!",
    },
    {
      type: "quiz",
      id: "boss-quiz",
      eyebrow: "🏆 Boss Quiz",
      title: "Master of Changes — final challenge",
      questions: [
        {
          questionId: "pcc-quiz-1",
          prompt: "Which of the following is a chemical change?",
          options: [
            { id: "a", label: "Lifting up a chair" },
            { id: "b", label: "Filling a glass with orange juice" },
            { id: "c", label: "Cooking a pot of rice" },
            { id: "d", label: "Bursting a balloon" },
          ],
          correct: "c",
          explain: "Cooking creates new substances — you can't un-cook rice!",
        },
        {
          questionId: "pcc-quiz-2",
          prompt: "The process of depositing a zinc layer on iron is called…",
          options: [
            { id: "a", label: "Galvanisation" },
            { id: "b", label: "Crystallisation" },
            { id: "c", label: "Rusting" },
            { id: "d", label: "Condensation" },
          ],
          correct: "a",
        },
        {
          questionId: "pcc-quiz-3",
          prompt: "Stainless steel is made of…",
          options: [
            { id: "a", label: "Iron, carbon, nickel and chromium" },
            { id: "b", label: "Iron, nickel and manganese" },
            { id: "c", label: "Only iron and carbon" },
            { id: "d", label: "Carbon, zinc and nickel" },
          ],
          correct: "a",
          explain: "Alloying iron with carbon, chromium and nickel gives steel that doesn't rust at all — your kitchen knives!",
        },
        {
          questionId: "pcc-quiz-4",
          prompt: "Which of these is NOT a sign of a chemical change?",
          options: [
            { id: "a", label: "Change in colour" },
            { id: "b", label: "Change in state" },
            { id: "c", label: "Production of sound" },
            { id: "d", label: "Change in smell" },
          ],
          correct: "b",
          explain: "Change of state (ice → water) is the classic PHYSICAL change — same substance, different costume.",
        },
        {
          questionId: "pcc-quiz-5",
          prompt: "The explosion of fireworks is…",
          options: [
            { id: "a", label: "A physical change" },
            { id: "b", label: "A chemical change" },
            { id: "c", label: "No change at all" },
            { id: "d", label: "A reversible change" },
          ],
          correct: "b",
        },
        {
          questionId: "pcc-quiz-6",
          prompt: "Melting of wax is a ___ change, while burning of wax is a ___ change.",
          options: [
            { id: "a", label: "physical … chemical" },
            { id: "b", label: "chemical … physical" },
            { id: "c", label: "physical … physical" },
            { id: "d", label: "chemical … chemical" },
          ],
          correct: "a",
          explain: "Melted wax is still wax (physical); burnt wax becomes CO₂ and water vapour (chemical).",
        },
        {
          questionId: "pcc-quiz-7",
          prompt: "Assertion (A): The burning of coal is a physical change.\nReason (R): When coal burns, its carbon changes to carbon dioxide, and this cannot be reversed.",
          options: [
            { id: "a", label: "Both A and R are true, and R explains A" },
            { id: "b", label: "Both A and R are true, but R does not explain A" },
            { id: "c", label: "A is true, but R is false" },
            { id: "d", label: "A is false, but R is true" },
          ],
          correct: "d",
          explain: "Burning coal makes a NEW substance (CO₂) — so it's chemical, making A false while R stays true.",
        },
        {
          questionId: "pcc-quiz-8",
          prompt: "An iron object (P) dipped in blue solution Q turns it green (R), and brown substance S — used for electric wires — coats the object. What are Q and S?",
          options: [
            { id: "a", label: "Q = copper sulphate, S = copper" },
            { id: "b", label: "Q = iron sulphate, S = zinc" },
            { id: "c", label: "Q = lime water, S = carbon" },
            { id: "d", label: "Q = copper sulphate, S = rust" },
          ],
          correct: "a",
          explain: "Iron pushes copper out of blue copper sulphate → green iron sulphate + brown copper on the nail. Straight from the Reaction Lab!",
        },
      ],
    },
    {
      type: "concept",
      id: "done",
      eyebrow: "🎉 Chapter Complete",
      title: "You are now a Master of Changes",
      body: "You pressed the universe's UNDO button, drove water through all three states, spotted the signs of chemical change, proved what rust needs and how to stop it, saved a bicycle and a tiffin box, and grew pure crystals. Physical or chemical — no change can fool you now!",
    },
  ],
  exercises: [
    // ——— True / False ———
    {
      questionId: "pcc-tf-1",
      prompt: "True or False: Rusting of iron is a physical change.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "b",
      explain: "Rusting forms a new substance (iron oxide), so it's a chemical change.",
    },
    {
      questionId: "pcc-tf-2",
      prompt: "True or False: Burning of a candle is a chemical change.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    {
      questionId: "pcc-tf-3",
      prompt: "True or False: Melting of ice is a reversible change.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    {
      questionId: "pcc-tf-4",
      prompt: "True or False: A chemical change can usually be reversed easily.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "b",
      explain: "Chemical changes are usually permanent — you can't un-burn paper.",
    },
    {
      questionId: "pcc-tf-5",
      prompt: "True or False: Crystallisation is a physical change.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    // ——— Fill in the blanks ———
    {
      questionId: "pcc-fb-1",
      prompt: "The formation of rust needs oxygen and ______.",
      qtype: "fill-blank",
      answers: ["water"],
    },
    {
      questionId: "pcc-fb-2",
      prompt: "Impure copper sulphate can be purified by the process of ______.",
      qtype: "fill-blank",
      answers: ["crystallisation", "crystallization"],
    },
    {
      questionId: "pcc-fb-3",
      prompt: "Coating iron with a layer of zinc to prevent rusting is called ______.",
      qtype: "fill-blank",
      answers: ["galvanisation", "galvanization"],
    },
    {
      questionId: "pcc-fb-4",
      prompt: "Melting of wax is a ______ change.",
      qtype: "fill-blank",
      answers: ["physical"],
    },
  ],
};
