import type { Chapter } from "../types";

// Class 7 Social Studies Ch. 3 (State Government) — "The Statehouse" hub build.
// The whole learning journey lives in the immersive `statehouse` custom scene
// (five explorable rooms + approval meter). A vocab scene keeps the Vocabulary
// deck; the boss quiz and the full exercises[] bank keep tracking/practice.
// Stable ids sg-quiz-* / sg-ex-*.
export const stateGovernmentChapter: Chapter = {
  slug: "state-government",
  title: "State Government",
  subject: "Social Studies",
  emoji: "🏛️",
  color: "#6c63ff",
  description: "Win an election, build a government, pilot a bill into law, and sit at the Governor's desk making the big decisions.",
  trophy: { emoji: "🏛️", name: "Statehouse Seal", caption: "Ran a whole state — from election to law-making to the Governor's chair." },
  scenes: [
    {
      type: "concept",
      id: "hook",
      eyebrow: "🏛️ Run the State",
      title: "Welcome to the Statehouse",
      body: "Who decides your school holidays, builds your roads, runs the police in your city? Not one person — a whole machine called the STATE GOVERNMENT. In the next screen you'll step inside the state's power building and explore it room by room: win an election, make a law, sit in the Governor's chair, run the Chief Minister's office and the civil service. Good decisions raise your Approval — clear every room to face the voters. Ready?",
    },
    { type: "custom", id: "statehouse", component: "statehouse", fullscreen: true },
    {
      type: "vocab",
      id: "keywords",
      eyebrow: "🔤 Civics Glossary",
      title: "Words to know",
      words: [
        { word: "State List", meaning: "Subjects on which only the state government can make laws." },
        { word: "Ordinance", meaning: "A temporary law issued by the Governor when the legislature is not in session." },
        { word: "Bicameral", meaning: "A legislature with two houses (Assembly and Council)." },
        { word: "Unicameral", meaning: "A legislature with only one house (the Assembly)." },
        { word: "Federal government", meaning: "Government at two levels — the Centre and the states." },
        { word: "Speaker", meaning: "The presiding officer (chairman) of the Vidhan Sabha." },
        { word: "Legislation", meaning: "The process of making and passing laws." },
        { word: "Constituency", meaning: "A voting area from which one MLA is elected." },
        { word: "MLA", meaning: "Member of the Legislative Assembly, elected directly by the people." },
        { word: "MLC", meaning: "Member of the Legislative Council (Vidhan Parishad)." },
        { word: "Divisions", meaning: "Administrative units into which a state is divided." },
        { word: "Portfolio", meaning: "The department a minister is placed in charge of." },
      ],
    },
    {
      type: "quiz",
      id: "boss-quiz",
      eyebrow: "🏆 Boss Quiz",
      title: "Run the State — the final test",
      questions: [
        {
          questionId: "sg-quiz-1",
          prompt: "Who acts as the constitutional head of the state?",
          options: [
            { id: "a", label: "Chief Minister" },
            { id: "b", label: "Governor" },
            { id: "c", label: "Prime Minister" },
            { id: "d", label: "Advocate-General" },
          ],
          correct: "b",
        },
        {
          questionId: "sg-quiz-2",
          prompt: "By whom is the Governor appointed?",
          options: [
            { id: "a", label: "The MLAs" },
            { id: "b", label: "The President of India" },
            { id: "c", label: "The people, by voting" },
            { id: "d", label: "The Chief Minister" },
          ],
          correct: "b",
        },
        {
          questionId: "sg-quiz-3",
          prompt: "No bill can become a law without the signature of the…",
          options: [
            { id: "a", label: "Governor" },
            { id: "b", label: "Minister" },
            { id: "c", label: "Officer" },
            { id: "d", label: "President" },
          ],
          correct: "a",
        },
        {
          questionId: "sg-quiz-4",
          prompt: "The process of making and passing laws is called…",
          options: [
            { id: "a", label: "Legislation" },
            { id: "b", label: "Billing" },
            { id: "c", label: "Writing" },
            { id: "d", label: "Election" },
          ],
          correct: "a",
        },
        {
          questionId: "sg-quiz-5",
          prompt: "A legislature with BOTH an Assembly and a Council is called…",
          options: [
            { id: "a", label: "Unicameral" },
            { id: "b", label: "Bicameral" },
            { id: "c", label: "Federal" },
            { id: "d", label: "Nominal" },
          ],
          correct: "b",
        },
        {
          questionId: "sg-quiz-6",
          prompt: "The Vidhan Parishad is special because it…",
          options: [
            { id: "a", label: "Is dissolved every 5 years" },
            { id: "b", label: "Is a permanent house — 1/3 retire every 2 years" },
            { id: "c", label: "Has no members" },
            { id: "d", label: "Is elected directly by all voters" },
          ],
          correct: "b",
        },
        {
          questionId: "sg-quiz-7",
          prompt: "If the Chief Minister resigns, what happens?",
          options: [
            { id: "a", label: "Nothing changes" },
            { id: "b", label: "Only the CM leaves" },
            { id: "c", label: "The whole Council of Ministers resigns" },
            { id: "d", label: "The Governor also resigns" },
          ],
          correct: "c",
          explain: "The CM's resignation means the resignation of the entire ministry.",
        },
        {
          questionId: "sg-quiz-8",
          prompt: "A Money Bill can be introduced only in the…",
          options: [
            { id: "a", label: "Vidhan Parishad" },
            { id: "b", label: "Vidhan Sabha" },
            { id: "c", label: "High Court" },
            { id: "d", label: "Governor's house" },
          ],
          correct: "b",
        },
        {
          questionId: "sg-quiz-9",
          prompt: "Changing a death sentence to life imprisonment is which power of the Governor?",
          options: [
            { id: "a", label: "Executive" },
            { id: "b", label: "Legislative" },
            { id: "c", label: "Judicial" },
            { id: "d", label: "Financial" },
          ],
          correct: "c",
        },
        {
          questionId: "sg-quiz-10",
          prompt: "The state is divided into administrative units called…",
          options: [
            { id: "a", label: "Constituencies" },
            { id: "b", label: "Divisions" },
            { id: "c", label: "Portfolios" },
            { id: "d", label: "Houses" },
          ],
          correct: "b",
        },
      ],
    },
    {
      type: "concept",
      id: "exercise-pointer",
      eyebrow: "📚 Homework Zone",
      title: "Full exercises are in your Practice Arena",
      body: "Every 'Practice Time' MCQ and fill-in from the chapter — and more — is in the Practice Arena under State Government, where XP, streaks and Today's Review all count.",
    },
    {
      type: "concept",
      id: "done",
      eyebrow: "🎉 Chapter Complete",
      title: "You ran the whole state!",
      body: "You won an election and formed a government, met both houses of the legislature, piloted a bill into a signed Act, and sat at the Governor's desk making the executive, legislative and judicial calls. The Statehouse Seal is yours!",
    },
  ],
  exercises: [
    // ——— Practice Time A (OMR MCQs) ———
    {
      questionId: "sg-ex-1",
      prompt: "The ___-General is appointed by the Governor.",
      options: [
        { id: "a", label: "High" },
        { id: "b", label: "Chief" },
        { id: "c", label: "Advocate" },
        { id: "d", label: "Prime Minister" },
      ],
      correct: "c",
      explain: "The Advocate-General is the state's legal adviser, appointed by the Governor.",
    },
    {
      questionId: "sg-ex-2",
      prompt: "The process of making and passing laws is called…",
      options: [
        { id: "a", label: "Legislation" },
        { id: "b", label: "Billing" },
        { id: "c", label: "Writing" },
        { id: "d", label: "None of these" },
      ],
      correct: "a",
    },
    {
      questionId: "sg-ex-3",
      prompt: "No bill can become law without the signature of the…",
      options: [
        { id: "a", label: "Governor" },
        { id: "b", label: "Minister" },
        { id: "c", label: "Officer" },
        { id: "d", label: "President" },
      ],
      correct: "a",
    },
    {
      questionId: "sg-ex-4",
      prompt: "___ acts as a constitutional head of the state.",
      options: [
        { id: "a", label: "Chief minister" },
        { id: "b", label: "Governor" },
        { id: "c", label: "Prime minister" },
        { id: "d", label: "Advocate" },
      ],
      correct: "b",
    },
    {
      questionId: "sg-ex-5",
      prompt: "By whom is the Governor appointed?",
      options: [
        { id: "a", label: "MLA" },
        { id: "b", label: "President" },
        { id: "c", label: "Central Government" },
        { id: "d", label: "None of these" },
      ],
      correct: "b",
    },
    // ——— Practice Time B (fill in the blanks, as MCQ) ———
    {
      questionId: "sg-ex-6",
      prompt: "The decisions of the ministers are actually executed by officers of the ___ service.",
      options: [
        { id: "a", label: "Military" },
        { id: "b", label: "Civil" },
        { id: "c", label: "Secret" },
        { id: "d", label: "Postal" },
      ],
      correct: "b",
    },
    {
      questionId: "sg-ex-7",
      prompt: "The ___ heads the civil service in a state.",
      options: [
        { id: "a", label: "Governor" },
        { id: "b", label: "Chief Secretary" },
        { id: "c", label: "District Magistrate" },
        { id: "d", label: "Speaker" },
      ],
      correct: "b",
    },
    {
      questionId: "sg-ex-8",
      prompt: "The state is divided into administrative units called…",
      options: [
        { id: "a", label: "Constituencies" },
        { id: "b", label: "Divisions" },
        { id: "c", label: "Houses" },
        { id: "d", label: "Councils" },
      ],
      correct: "b",
    },
    // ——— Extra coverage ———
    {
      questionId: "sg-ex-9",
      prompt: "The members of the Legislative Assembly are called…",
      options: [
        { id: "a", label: "MPs" },
        { id: "b", label: "MLCs" },
        { id: "c", label: "MLAs" },
        { id: "d", label: "IAS officers" },
      ],
      correct: "c",
    },
    {
      questionId: "sg-ex-10",
      prompt: "The presiding officer of the Vidhan Sabha is the…",
      options: [
        { id: "a", label: "Chairman" },
        { id: "b", label: "Speaker" },
        { id: "c", label: "Governor" },
        { id: "d", label: "Chief Minister" },
      ],
      correct: "b",
      explain: "The Speaker presides over the Vidhan Sabha; the Chairman presides over the Vidhan Parishad.",
    },
    {
      questionId: "sg-ex-11",
      prompt: "A temporary law issued by the Governor when the legislature is not in session is called a/an…",
      options: [
        { id: "a", label: "Bill" },
        { id: "b", label: "Act" },
        { id: "c", label: "Ordinance" },
        { id: "d", label: "Amendment" },
      ],
      correct: "c",
    },
    {
      questionId: "sg-ex-12",
      prompt: "The minimum age to become a member of the Vidhan Parishad is…",
      options: [
        { id: "a", label: "25 years" },
        { id: "b", label: "30 years" },
        { id: "c", label: "35 years" },
        { id: "d", label: "21 years" },
      ],
      correct: "b",
    },
    {
      questionId: "sg-ex-13",
      prompt: "Which states have a bicameral legislature? (has BOTH houses)",
      options: [
        { id: "a", label: "Kerala and Gujarat" },
        { id: "b", label: "Uttar Pradesh and Bihar" },
        { id: "c", label: "Goa and Sikkim" },
        { id: "d", label: "Rajasthan and Punjab" },
      ],
      correct: "b",
      explain: "UP, Bihar, Maharashtra, Karnataka, Andhra Pradesh and J&K are bicameral; most others are unicameral.",
    },
    {
      questionId: "sg-ex-14",
      prompt: "The term of the Legislative Assembly (Vidhan Sabha) is…",
      options: [
        { id: "a", label: "4 years" },
        { id: "b", label: "5 years" },
        { id: "c", label: "6 years" },
        { id: "d", label: "Permanent" },
      ],
      correct: "b",
      explain: "5 years — though it can be dissolved earlier. (The Vidhan Parishad is permanent.)",
    },
    {
      questionId: "sg-ex-15",
      prompt: "A Money Bill can be introduced only in the…",
      options: [
        { id: "a", label: "Vidhan Parishad" },
        { id: "b", label: "Vidhan Sabha" },
        { id: "c", label: "Governor's office" },
        { id: "d", label: "Supreme Court" },
      ],
      correct: "b",
    },
    {
      questionId: "sg-ex-16",
      prompt: "One-third of the members of the Vidhan Parishad retire every…",
      options: [
        { id: "a", label: "Year" },
        { id: "b", label: "Two years" },
        { id: "c", label: "Five years" },
        { id: "d", label: "Six years" },
      ],
      correct: "b",
      explain: "1/3 retire every 2 years; each member's term is 6 years.",
    },
    {
      questionId: "sg-ex-17",
      prompt: "The Chief Minister is the leader of the…",
      options: [
        { id: "a", label: "Opposition party" },
        { id: "b", label: "Majority party in the Vidhan Sabha" },
        { id: "c", label: "Civil service" },
        { id: "d", label: "Judiciary" },
      ],
      correct: "b",
    },
    {
      questionId: "sg-ex-18",
      prompt: "Uttar Pradesh is divided into how many constituencies?",
      options: [
        { id: "a", label: "200" },
        { id: "b", label: "300" },
        { id: "c", label: "403" },
        { id: "d", label: "500" },
      ],
      correct: "c",
    },
    // ——— True / False ———
    {
      questionId: "sg-tf-1",
      prompt: "True or False: The Governor is elected directly by the people.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "b",
      explain: "The Governor is appointed by the President of India, not elected.",
    },
    {
      questionId: "sg-tf-2",
      prompt: "True or False: A Money Bill can be introduced in the Vidhan Parishad.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "b",
      explain: "Money Bills can be introduced only in the Vidhan Sabha.",
    },
    {
      questionId: "sg-tf-3",
      prompt: "True or False: The Vidhan Parishad is a permanent house that is never fully dissolved.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    {
      questionId: "sg-tf-4",
      prompt: "True or False: No bill can become a law in a state without the Governor's signature.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    {
      questionId: "sg-tf-5",
      prompt: "True or False: If the Chief Minister resigns, the whole Council of Ministers resigns too.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    // ——— Fill in the blanks ———
    {
      questionId: "sg-fb-1",
      prompt: "The nominal (constitutional) head of a state is the ______.",
      qtype: "fill-blank",
      answers: ["governor"],
    },
    {
      questionId: "sg-fb-2",
      prompt: "The lower house of the state legislature is called the Vidhan ______.",
      qtype: "fill-blank",
      answers: ["sabha"],
    },
    {
      questionId: "sg-fb-3",
      prompt: "A temporary law issued by the Governor when the legislature is not in session is called an ______.",
      qtype: "fill-blank",
      answers: ["ordinance"],
    },
    {
      questionId: "sg-fb-4",
      prompt: "The officer who heads the civil service in a state is the Chief ______.",
      qtype: "fill-blank",
      answers: ["secretary"],
    },
    {
      questionId: "sg-fb-5",
      prompt: "The state's legal adviser, appointed by the Governor, is the ______-General.",
      qtype: "fill-blank",
      answers: ["advocate"],
    },
  ],
};
