import type { Chapter } from "../types";

// Class 7 Social Studies Ch. 3 (State Government). Frame: "Run the State".
// Stable ids sg-bq-* / sg-quiz-* / sg-ex-*.
export const stateGovernmentChapter: Chapter = {
  slug: "state-government",
  title: "State Government",
  subject: "Social Studies",
  emoji: "🏛️",
  color: "#6c63ff",
  description: "Step inside the state's power machine — meet the Assembly, the Governor and the Chief Minister, and pilot a bill all the way to becoming law.",
  trophy: { emoji: "🏛️", name: "Statehouse Seal", caption: "Learned how a state is governed and piloted a bill from draft to law." },
  scenes: [
    {
      type: "concept",
      id: "hook",
      eyebrow: "🏛️ Run the State",
      title: "Who runs your state?",
      body: "India is a federal union of 28 states and 8 union territories, so government works at TWO levels — one at the Centre (for the whole nation) and one in each state. Just like the Centre, every state government has three organs: the executive, the legislature and the judiciary. Today you step inside the state's power machine and even pilot a law into existence.",
    },
    {
      type: "concept",
      id: "legislature-houses",
      eyebrow: "🏢 Two Houses",
      title: "The State Legislature",
      body: "Every state has a Legislative Assembly (Vidhan Sabha). Some states ALSO have a second house, the Legislative Council (Vidhan Parishad). Tap the cards.",
      cards: [
        { icon: "🏛️", front: "Bicameral", back: "A legislature with BOTH houses (Assembly + Council). e.g. UP, Bihar, Maharashtra, Karnataka, Andhra Pradesh, J&K." },
        { icon: "🏠", front: "Unicameral", back: "A legislature with ONLY the Assembly. Most states are unicameral." },
      ],
    },
    {
      type: "concept",
      id: "vidhan-sabha",
      eyebrow: "🗳️ The Lower House",
      title: "Legislative Assembly (Vidhan Sabha)",
      body: "The Vidhan Sabha is the lower house. Its members, the MLAs, are directly elected by the people and form the government. Its term is 5 years (but it can be dissolved earlier). Each state is split into areas called constituencies — Uttar Pradesh, for example, has 403! The constitution says an Assembly can have at most 500 members and at least 60 (special cases: Goa and Mizoram have 40, Sikkim has 32).",
    },
    {
      type: "concept",
      id: "vidhan-parishad",
      eyebrow: "🏛️ The Upper House",
      title: "Legislative Council (Vidhan Parishad)",
      body: "The Vidhan Parishad is the upper house, found only in some states. Its members are MLCs. Unlike the Assembly, it is a PERMANENT house that can never be fully dissolved — one-third of its members retire every two years, each serving a 6-year term. It must have at least 40 members, elected by the Vidhan Sabha, local bodies, teachers and graduates — plus some nominated by the Governor for their work in art, literature, science or social service.",
    },
    {
      type: "match",
      id: "houses-match",
      eyebrow: "🎮 Sort the Houses",
      title: "Assembly or Council?",
      prompt: "Tap a fact, then tap which house it describes.",
      pairs: [
        { left: "Lower house, term 5 years", right: "Vidhan Sabha" },
        { left: "Members are MLAs", right: "Vidhan Sabha" },
        { left: "Permanent house, never fully dissolved", right: "Vidhan Parishad" },
        { left: "Members are MLCs", right: "Vidhan Parishad" },
      ],
    },
    {
      type: "concept",
      id: "qualifications",
      eyebrow: "✅ Who Can Stand?",
      title: "Qualifications and presiding officers",
      body: "To be a member of a state legislature you must be an Indian citizen, of sound mind, and not hold an office of profit. Age: at least 25 for the Vidhan Sabha, at least 30 for the Vidhan Parishad. Each house has presiding officers who keep order: the Speaker & Deputy Speaker run the Vidhan Sabha; the Chairman & Deputy Chairman run the Vidhan Parishad. They vote only to break a tie.",
    },
    {
      type: "book-question",
      id: "bq-1",
      questionId: "sg-bq-1",
      eyebrow: "📖 Practice",
      prompt: "A member of the Vidhan Sabha must be at least how old?",
      options: [
        { id: "a", label: "18 years" },
        { id: "b", label: "21 years" },
        { id: "c", label: "25 years" },
        { id: "d", label: "30 years" },
      ],
      correct: "c",
      explain: "Minimum age is 25 for the Vidhan Sabha (and 30 for the Vidhan Parishad).",
    },
    { type: "custom", id: "bill-to-act", component: "bill-to-act" },
    {
      type: "concept",
      id: "governor",
      eyebrow: "👤 The Nominal Head",
      title: "The Governor",
      body: "The Governor is the nominal (constitutional) head of the state executive — like the President is for the nation. The Governor is appointed by the President of India for a 5-year term. To be eligible you must be an Indian citizen, at least 35 years old, hold no office of profit, and not be a sitting MP or MLA. All state administration is carried out in the Governor's name.",
    },
    {
      type: "sort",
      id: "governor-powers-sort",
      eyebrow: "🗂️ The Governor's Powers",
      title: "Which kind of power?",
      prompt: "The Governor has three kinds of power. Sort each action.",
      buckets: ["Executive / Legislative", "Judicial"],
      items: [
        { label: "Appoints the Chief Minister", bucket: 0 },
        { label: "Summons & adjourns the legislature", bucket: 0 },
        { label: "Signs bills into Acts", bucket: 0 },
        { label: "Issues ordinances when the House isn't sitting", bucket: 0 },
        { label: "Pardons or commutes a punishment", bucket: 1 },
        { label: "Changes a death penalty to life imprisonment", bucket: 1 },
      ],
    },
    {
      type: "concept",
      id: "ordinance",
      eyebrow: "⚡ Emergency Law",
      title: "The ordinance power",
      body: "When the state legislature is NOT in session and a law is urgently needed, the Governor can issue an ordinance — a temporary law with the same force as an Act. But it's not permanent: the ordinance must be approved (ratified) by the legislature within six weeks of its next session, or it dies on its own.",
    },
    {
      type: "concept",
      id: "chief-minister",
      eyebrow: "💼 The Real Ruler",
      title: "Chief Minister & Council of Ministers",
      body: "The Governor appoints the leader of the majority party as Chief Minister, who then picks the other ministers. In practice the Chief Minister is the real head of the state — the vital link between the Governor and the legislature. Tap the CM's main jobs.",
      cards: [
        { icon: "🧭", front: "Direct", back: "Directs the ministry and decides its policies." },
        { icon: "📂", front: "Allocate", back: "Allocates, reallocates or takes back portfolios (departments) from ministers." },
        { icon: "🤝", front: "Coordinate", back: "Coordinates the work of the various ministers so government runs smoothly." },
        { icon: "👀", front: "Supervise", back: "Supervises the whole administration of the state." },
      ],
    },
    {
      type: "concept",
      id: "civil-services",
      eyebrow: "🧑‍💼 The Executors",
      title: "Civil Services",
      body: "Ministers make the decisions, but the civil service actually carries them out. Officers like the IAS (Indian Administrative Service) and IPS (Indian Police Service) run the administration; the state Public Service Commission (PSC) also selects officials. The Chief Secretary heads the civil service in a state. The state is divided into administrative units called divisions (looked after by Divisional Commissioners), which split into districts run by District Magistrates.",
    },
    {
      type: "book-question",
      id: "bq-2",
      questionId: "sg-bq-2",
      eyebrow: "📖 Practice",
      prompt: "Who heads the civil service in a state?",
      options: [
        { id: "a", label: "The Governor" },
        { id: "b", label: "The Chief Secretary" },
        { id: "c", label: "The Advocate-General" },
        { id: "d", label: "The District Magistrate" },
      ],
      correct: "b",
      explain: "The Chief Secretary heads the state civil service; secretaries and directors work under them.",
    },
    {
      type: "concept",
      id: "advocate-general",
      eyebrow: "⚖️ The Legal Adviser",
      title: "The Advocate-General",
      body: "Each state has an official called the Advocate-General who advises the state executive on legal matters. Appointed by the Governor, they hold office 'during the pleasure of the Governor'. Only someone qualified to be a High Court judge is eligible. The Advocate-General can take part in the proceedings of the State Legislature but cannot vote.",
    },
    {
      type: "vocab",
      id: "keywords",
      eyebrow: "🔤 Words to Know",
      title: "Civics glossary",
      words: [
        { word: "State List", meaning: "A list of subjects on which only the state government can make laws." },
        { word: "Ordinance", meaning: "A temporary law issued by the Governor when the legislature is not in session." },
        { word: "Bicameral", meaning: "A legislature with two houses (Assembly and Council)." },
        { word: "Unicameral", meaning: "A legislature with only one house (the Assembly)." },
        { word: "Federal government", meaning: "Government at two levels — the Centre and the states." },
        { word: "Speaker", meaning: "The presiding officer of the Vidhan Sabha." },
        { word: "Legislation", meaning: "The process of making and passing laws." },
        { word: "Constituency", meaning: "An area of a state from which one representative (MLA) is elected." },
        { word: "MLA", meaning: "Member of the Legislative Assembly, elected directly by the people." },
        { word: "Divisions", meaning: "Administrative units into which a state is divided." },
      ],
    },
    {
      type: "quiz",
      id: "boss-quiz",
      eyebrow: "🏆 Boss Quiz",
      title: "Run the State — final test",
      questions: [
        {
          questionId: "sg-quiz-1",
          prompt: "Who acts as the constitutional head of the state?",
          options: [
            { id: "a", label: "Chief Minister" },
            { id: "b", label: "Governor" },
            { id: "c", label: "Prime Minister" },
            { id: "d", label: "Advocate-General" },
          ],
          correct: "b",
        },
        {
          questionId: "sg-quiz-2",
          prompt: "By whom is the Governor appointed?",
          options: [
            { id: "a", label: "MLAs" },
            { id: "b", label: "The President of India" },
            { id: "c", label: "The Central Government by vote" },
            { id: "d", label: "The Chief Minister" },
          ],
          correct: "b",
        },
        {
          questionId: "sg-quiz-3",
          prompt: "No bill can become a law without the signature of the…",
          options: [
            { id: "a", label: "Governor" },
            { id: "b", label: "Minister" },
            { id: "c", label: "Officer" },
            { id: "d", label: "President" },
          ],
          correct: "a",
          explain: "In a state, a passed bill becomes an Act only when the Governor signs it.",
        },
        {
          questionId: "sg-quiz-4",
          prompt: "The process of making and passing laws is called…",
          options: [
            { id: "a", label: "Legislation" },
            { id: "b", label: "Billing" },
            { id: "c", label: "Writing" },
            { id: "d", label: "Election" },
          ],
          correct: "a",
        },
        {
          questionId: "sg-quiz-5",
          prompt: "The Legislative Council is also known as the…",
          options: [
            { id: "a", label: "Vidhan Sabha" },
            { id: "b", label: "Lok Sabha" },
            { id: "c", label: "Vidhan Parishad" },
            { id: "d", label: "Rajya Sabha" },
          ],
          correct: "c",
        },
        {
          questionId: "sg-quiz-6",
          prompt: "A legislature with both an Assembly and a Council is called…",
          options: [
            { id: "a", label: "Unicameral" },
            { id: "b", label: "Bicameral" },
            { id: "c", label: "Federal" },
            { id: "d", label: "Nominal" },
          ],
          correct: "b",
        },
        {
          questionId: "sg-quiz-7",
          prompt: "The Chief Minister is the leader of the…",
          options: [
            { id: "a", label: "Opposition party" },
            { id: "b", label: "Majority party in the Vidhan Sabha" },
            { id: "c", label: "Civil service" },
            { id: "d", label: "Judiciary" },
          ],
          correct: "b",
          explain: "The Governor appoints the leader of the majority party as Chief Minister.",
        },
      ],
    },
    {
      type: "concept",
      id: "exercise-pointer",
      eyebrow: "📚 Homework Zone",
      title: "Full exercises are in your Practice Arena",
      body: "Every 'Practice Time' MCQ and fill-in from the chapter is in the Practice Arena under State Government — where XP, streaks and Today's Review all count.",
    },
    {
      type: "concept",
      id: "done",
      eyebrow: "🎉 Chapter Complete",
      title: "You know how a state runs",
      body: "You met both houses of the legislature, learned the Governor's three powers, saw how the Chief Minister and civil service actually run things, and piloted a bill all the way from a draft to a signed Act. The Statehouse Seal is yours!",
    },
  ],
  exercises: [
    {
      questionId: "sg-ex-1",
      prompt: "The ___-General is appointed by the Governor.",
      options: [
        { id: "a", label: "High" },
        { id: "b", label: "Chief" },
        { id: "c", label: "Advocate" },
        { id: "d", label: "Prime Minister" },
      ],
      correct: "c",
      explain: "The Advocate-General is the state's legal adviser, appointed by the Governor.",
    },
    {
      questionId: "sg-ex-2",
      prompt: "The process of making and passing laws is called…",
      options: [
        { id: "a", label: "Legislation" },
        { id: "b", label: "Billing" },
        { id: "c", label: "Writing" },
        { id: "d", label: "None of these" },
      ],
      correct: "a",
    },
    {
      questionId: "sg-ex-3",
      prompt: "No bill can become law without the signature of the…",
      options: [
        { id: "a", label: "Governor" },
        { id: "b", label: "Minister" },
        { id: "c", label: "Officer" },
        { id: "d", label: "President" },
      ],
      correct: "a",
    },
    {
      questionId: "sg-ex-4",
      prompt: "___ acts as a constitutional head of the state.",
      options: [
        { id: "a", label: "Chief minister" },
        { id: "b", label: "Governor" },
        { id: "c", label: "Prime minister" },
        { id: "d", label: "Advocate" },
      ],
      correct: "b",
    },
    {
      questionId: "sg-ex-5",
      prompt: "By whom is the Governor appointed?",
      options: [
        { id: "a", label: "MLA" },
        { id: "b", label: "President" },
        { id: "c", label: "Central Government" },
        { id: "d", label: "None of these" },
      ],
      correct: "b",
    },
    {
      questionId: "sg-ex-6",
      prompt: "The decisions of the ministers are actually executed by officers of the ___ service.",
      options: [
        { id: "a", label: "Military" },
        { id: "b", label: "Civil" },
        { id: "c", label: "Secret" },
        { id: "d", label: "Postal" },
      ],
      correct: "b",
    },
    {
      questionId: "sg-ex-7",
      prompt: "The ___ heads the civil service in a state.",
      options: [
        { id: "a", label: "Governor" },
        { id: "b", label: "Chief Secretary" },
        { id: "c", label: "District Magistrate" },
        { id: "d", label: "Speaker" },
      ],
      correct: "b",
    },
    {
      questionId: "sg-ex-8",
      prompt: "The state is divided into administrative units called…",
      options: [
        { id: "a", label: "Constituencies" },
        { id: "b", label: "Divisions" },
        { id: "c", label: "Houses" },
        { id: "d", label: "Councils" },
      ],
      correct: "b",
      explain: "Divisions (run by Divisional Commissioners) further split into districts.",
    },
    {
      questionId: "sg-ex-9",
      prompt: "The members of the Legislative Assembly are called…",
      options: [
        { id: "a", label: "MPs" },
        { id: "b", label: "MLCs" },
        { id: "c", label: "MLAs" },
        { id: "d", label: "IAS officers" },
      ],
      correct: "c",
    },
    {
      questionId: "sg-ex-10",
      prompt: "The presiding officer of the Vidhan Sabha is the…",
      options: [
        { id: "a", label: "Chairman" },
        { id: "b", label: "Speaker" },
        { id: "c", label: "Governor" },
        { id: "d", label: "Chief Minister" },
      ],
      correct: "b",
      explain: "The Speaker (with the Deputy Speaker) presides over the Vidhan Sabha; the Chairman presides over the Vidhan Parishad.",
    },
    {
      questionId: "sg-ex-11",
      prompt: "A temporary law issued by the Governor when the legislature is not in session is called a/an…",
      options: [
        { id: "a", label: "Bill" },
        { id: "b", label: "Act" },
        { id: "c", label: "Ordinance" },
        { id: "d", label: "Amendment" },
      ],
      correct: "c",
    },
    {
      questionId: "sg-ex-12",
      prompt: "The minimum age to become a member of the Vidhan Parishad is…",
      options: [
        { id: "a", label: "25 years" },
        { id: "b", label: "30 years" },
        { id: "c", label: "35 years" },
        { id: "d", label: "21 years" },
      ],
      correct: "b",
      explain: "30 for the Vidhan Parishad; 25 for the Vidhan Sabha; 35 for the Governor.",
    },
  ],
};
