import type { Chapter } from "../types";

// Class 7 Science Ch. 3 (Temperature and Heat). Frame: "The Heat Detective".
// Stable ids th-bq-* / th-quiz-* / th-ex-*.
export const temperatureAndHeatChapter: Chapter = {
  slug: "temperature-and-heat",
  title: "Temperature and Heat",
  subject: "Science",
  emoji: "🌡️",
  color: "#ef9f27",
  description: "Read the three thermometer scales, catch heat moving three secret ways, and learn how a thermos outsmarts them all.",
  trophy: { emoji: "🌡️", name: "Heat Detective Badge", caption: "Measured every scale and caught heat conducting, convecting and radiating." },
  scenes: [
    {
      type: "concept",
      id: "hook",
      eyebrow: "🔍 The Heat Detective",
      title: "You can't see it, but you can feel it",
      body: "Ice melts, water boils, a feverish forehead burns — all because of something invisible: HEAT. You can't see it like light, only feel it. Today you become a heat detective: measure exactly how hot things are, catch heat sneaking from place to place in three secret ways, and learn how a thermos flask blocks all of them.",
    },
    {
      type: "concept",
      id: "temperature",
      eyebrow: "🤔 Why Not Just Touch?",
      title: "Temperature: the degree of hotness",
      body: "Temperature is how hot or cold a body is. But your hand is a liar! Dip one finger in ice water and another in hot water, then both into lukewarm water — the same water feels hot to one finger and cold to the other. Touch is relative, so to know the REAL temperature we need a proper instrument: a thermometer.",
    },
    {
      type: "concept",
      id: "thermometer-types",
      eyebrow: "🌡️ The Detective's Tools",
      title: "Types of thermometers",
      body: "A thermometer measures temperature. Tap each type to see where it shines.",
      cards: [
        { icon: "🥈", front: "Mercury", back: "Liquid over a wide range, high boiling point, doesn't stick to glass, easy to see. Freezes at −38°C." },
        { icon: "🍷", front: "Alcohol", back: "Cheaper than mercury and measures very LOW temperatures (down to −115°C)." },
        { icon: "🧪", front: "Laboratory", back: "Long glass tube, range about −10°C to 110°C, for experiments." },
        { icon: "🩺", front: "Clinical", back: "Measures body temperature (35°C to 42°C). Has a kink so the reading doesn't fall until you shake it." },
      ],
    },
    { type: "custom", id: "temp-converter", component: "temp-converter" },
    {
      type: "concept",
      id: "scales",
      eyebrow: "📏 Three Scales",
      title: "Celsius, Fahrenheit and Kelvin",
      body: "Three scales, three inventors — tap each. The fixed points are where water freezes (lower) and boils (upper).",
      cards: [
        { icon: "🇸🇪", front: "Celsius (°C)", back: "By Anders Celsius. Water freezes at 0°C (lower fixed point), boils at 100°C (upper). 100 divisions between." },
        { icon: "🇩🇪", front: "Fahrenheit (°F)", back: "By Daniel Fahrenheit. Water freezes at 32°F, boils at 212°F. 180 divisions between." },
        { icon: "🇬🇧", front: "Kelvin (K)", back: "By Lord Kelvin. The SI standard unit. 0°C ≈ 273 K. A change of 1 K = a change of 1°C." },
      ],
    },
    {
      type: "book-question",
      id: "bq-1",
      questionId: "th-bq-1",
      eyebrow: "📖 Practice",
      prompt: "The normal temperature of a healthy human body is thirty-seven degrees on which scale?",
      options: [
        { id: "a", label: "Kelvin scale" },
        { id: "b", label: "Roemer scale" },
        { id: "c", label: "Fahrenheit scale" },
        { id: "d", label: "Celsius scale" },
      ],
      correct: "d",
      explain: "Normal body temperature is 37°C (which equals 98.6°F).",
    },
    {
      type: "concept",
      id: "heat-flow",
      eyebrow: "🔥 What Is Heat?",
      title: "Heat always flows hot → cold",
      body: "Heat is a form of ENERGY that flows from a hotter body to a colder one. Dip your finger in a glass of ice water — heat flows FROM your warm finger TO the water, so your finger feels cold. In hot water, heat flows the other way, so it feels hot. Heat is measured in calories and joules: 1 calorie ≈ 4.2 joules.",
    },
    {
      type: "concept",
      id: "three-ways",
      eyebrow: "🕵️ Three Secret Routes",
      title: "How heat travels",
      body: "Heat sneaks from place to place in exactly three ways. Tap each — you'll catch them in action next.",
      cards: [
        { icon: "🥄", front: "Conduction", back: "Through solids: heated particles vibrate and pass energy to neighbours. Metals are good conductors." },
        { icon: "🌊", front: "Convection", back: "In liquids and gases: hot fluid rises, cool fluid sinks, setting up a current that carries heat." },
        { icon: "☀️", front: "Radiation", back: "Through waves — needs NO medium. This is how the Sun's heat crosses empty space to reach Earth." },
      ],
    },
    {
      type: "concept",
      id: "conduction",
      eyebrow: "🥄 Conduction",
      title: "Conductors and insulators",
      body: "Touch a metal spoon left in hot tea — the handle gets hot even though only the tip was in the tea. That's conduction: heat passing solid-to-solid. Materials that let heat pass easily are conductors (metals); those that don't are insulators (rubber, plastic, glass, wood, air). That's why a frying pan is metal but its handle is plastic or wood!",
    },
    {
      type: "sort",
      id: "conductor-sort",
      eyebrow: "🗂️ Sort It",
      title: "Conductor or insulator?",
      prompt: "Sort each material by whether heat passes through it easily.",
      buckets: ["Conductor 🔥", "Insulator 🧤"],
      items: [
        { label: "Iron", bucket: 0 },
        { label: "Copper", bucket: 0 },
        { label: "Wood", bucket: 1 },
        { label: "Plastic", bucket: 1 },
        { label: "Aluminium", bucket: 0 },
        { label: "Wool / trapped air", bucket: 1 },
      ],
    },
    {
      type: "concept",
      id: "convection",
      eyebrow: "🌊 Convection",
      title: "Currents of moving fluid",
      body: "Heat a beaker of water and the bottom layer warms first, becomes lighter, and RISES; cooler heavier water sinks to take its place. This endless loop is a convection current. It's why room heaters warm a whole room, why ventilators go high on the wall (hot air rises), and why we get sea and land breezes — air moving as it heats and cools.",
    },
    {
      type: "match",
      id: "convection-match",
      eyebrow: "🎮 Everyday Convection",
      title: "Match the fact to the reason",
      prompt: "Tap a scene, then tap the convection reason.",
      pairs: [
        { left: "Sea breeze (daytime)", right: "Land heats faster; cool sea air rushes in" },
        { left: "Land breeze (night)", right: "Land cools faster; cool land air moves to sea" },
        { left: "Ventilators near the ceiling", right: "Warm used air rises and escapes" },
        { left: "Water boils evenly in a pan", right: "Hot water rises, cool water sinks in a loop" },
      ],
    },
    {
      type: "concept",
      id: "radiation",
      eyebrow: "☀️ Radiation",
      title: "Heat that needs no medium",
      body: "The Sun's heat crosses millions of km of empty space — no solid, liquid or gas to carry it. That's radiation: heat travelling as waves. Dark, dull surfaces absorb and emit radiation well; light, shiny surfaces reflect it. That's why we wear dark clothes in winter (absorb more heat) and light clothes in summer (reflect it away).",
    },
    {
      type: "book-question",
      id: "bq-2",
      questionId: "th-bq-2",
      eyebrow: "📖 Practice",
      prompt: "The heat from the Sun reaches us on the Earth through the process of…",
      options: [
        { id: "a", label: "Conduction" },
        { id: "b", label: "Convection" },
        { id: "c", label: "Radiation" },
        { id: "d", label: "None of these" },
      ],
      correct: "c",
      explain: "Only radiation can cross the empty space between the Sun and Earth — it needs no medium.",
    },
    {
      type: "concept",
      id: "thermos",
      eyebrow: "🧴 Beating All Three",
      title: "How a thermos flask keeps heat in",
      body: "A thermos flask is a genius at blocking every route heat could take. Tap the cards.",
      cards: [
        { icon: "🧱", front: "Plastic & cork", back: "The outer cover and cap are insulators — they block CONDUCTION." },
        { icon: "🕳️", front: "Vacuum gap", back: "The double wall has a vacuum between — no particles means no CONVECTION." },
        { icon: "🪞", front: "Silvered walls", back: "Shiny mirror-like surfaces reflect heat back in — they block RADIATION." },
      ],
    },
    {
      type: "vocab",
      id: "keywords",
      eyebrow: "🔤 Detective's Glossary",
      title: "Words to know",
      words: [
        { word: "Temperature", meaning: "The degree of hotness or coldness of a body." },
        { word: "Thermometer", meaning: "An instrument used to measure temperature." },
        { word: "Heat", meaning: "A form of energy that flows from a hotter body to a colder one." },
        { word: "Conduction", meaning: "Transfer of heat through a solid, particle to particle." },
        { word: "Convection", meaning: "Transfer of heat in a fluid by the movement of its particles." },
        { word: "Radiation", meaning: "Transfer of heat as waves, needing no medium." },
        { word: "Conductor", meaning: "A material that lets heat pass through easily (e.g. metal)." },
        { word: "Insulator", meaning: "A material that does not let heat pass through easily (e.g. wool, plastic)." },
        { word: "Upper fixed point", meaning: "The boiling point of water on a scale (100°C / 212°F)." },
        { word: "Lower fixed point", meaning: "The freezing point of water on a scale (0°C / 32°F)." },
      ],
    },
    {
      type: "quiz",
      id: "boss-quiz",
      eyebrow: "🏆 Boss Quiz",
      title: "Heat Detective — final case",
      questions: [
        {
          questionId: "th-quiz-1",
          prompt: "The transfer of heat in a solid is called…",
          options: [
            { id: "a", label: "Conduction" },
            { id: "b", label: "Convection" },
            { id: "c", label: "Radiation" },
            { id: "d", label: "Dispersion" },
          ],
          correct: "a",
        },
        {
          questionId: "th-quiz-2",
          prompt: "The transfer of heat in a liquid is called…",
          options: [
            { id: "a", label: "Radiation" },
            { id: "b", label: "Convection" },
            { id: "c", label: "Conduction" },
            { id: "d", label: "Refraction" },
          ],
          correct: "b",
        },
        {
          questionId: "th-quiz-3",
          prompt: "The transfer of heat in the form of waves is called…",
          options: [
            { id: "a", label: "Radiation" },
            { id: "b", label: "Convection" },
            { id: "c", label: "Conduction" },
            { id: "d", label: "Dispersion" },
          ],
          correct: "a",
        },
        {
          questionId: "th-quiz-4",
          prompt: "A thermometer used to measure temperature in a laboratory is a…",
          options: [
            { id: "a", label: "Laboratory thermometer" },
            { id: "b", label: "Clinical thermometer" },
            { id: "c", label: "Speedometer" },
            { id: "d", label: "None of these" },
          ],
          correct: "a",
        },
        {
          questionId: "th-quiz-5",
          prompt: "The symbol for Fahrenheit is…",
          options: [
            { id: "a", label: "°C" },
            { id: "b", label: "°F" },
            { id: "c", label: "K" },
            { id: "d", label: "°K" },
          ],
          correct: "b",
        },
        {
          questionId: "th-quiz-6",
          prompt: "Which of the following is NOT an insulator?",
          options: [
            { id: "a", label: "Brick" },
            { id: "b", label: "Bamboo" },
            { id: "c", label: "Brass" },
            { id: "d", label: "Cardboard" },
          ],
          correct: "c",
          explain: "Brass is a metal — a good conductor, not an insulator.",
        },
        {
          questionId: "th-quiz-7",
          prompt: "Woollen clothes keep us warm in winter mainly because…",
          options: [
            { id: "a", label: "Wool is a conductor" },
            { id: "b", label: "Wool traps air (a poor conductor)" },
            { id: "c", label: "Wool has a vacuum" },
            { id: "d", label: "Wool radiates heat" },
          ],
          correct: "b",
          explain: "Air trapped between wool fibres is a poor conductor, so body heat can't escape.",
        },
      ],
    },
    {
      type: "concept",
      id: "exercise-pointer",
      eyebrow: "📚 Homework Zone",
      title: "Full exercises are in your Practice Arena",
      body: "Every MCQ from the chapter exercise is in the Practice Arena under Temperature and Heat — where XP, streaks and Today's Review all count.",
    },
    {
      type: "concept",
      id: "done",
      eyebrow: "🎉 Chapter Complete",
      title: "Case closed, detective!",
      body: "You measured temperature on three scales, converted between them, and caught heat travelling by conduction, convection and radiation — then watched a thermos flask block all three. The Heat Detective Badge is yours!",
    },
  ],
  exercises: [
    {
      questionId: "th-ex-1",
      prompt: "The transfer of heat in a liquid is called…",
      options: [
        { id: "a", label: "Radiation" },
        { id: "b", label: "Convection" },
        { id: "c", label: "Refraction" },
        { id: "d", label: "Conduction" },
      ],
      correct: "b",
    },
    {
      questionId: "th-ex-2",
      prompt: "The transfer of heat in a solid is called…",
      options: [
        { id: "a", label: "Conduction" },
        { id: "b", label: "Dispersion" },
        { id: "c", label: "Radiation" },
        { id: "d", label: "Convection" },
      ],
      correct: "a",
    },
    {
      questionId: "th-ex-3",
      prompt: "The transfer of heat in the form of waves is called…",
      options: [
        { id: "a", label: "Radiation" },
        { id: "b", label: "Convection" },
        { id: "c", label: "Filtration" },
        { id: "d", label: "Dispersion" },
      ],
      correct: "a",
    },
    {
      questionId: "th-ex-4",
      prompt: "A thermometer used to measure the temperature in a laboratory is a…",
      options: [
        { id: "a", label: "Laboratory thermometer" },
        { id: "b", label: "Clinical thermometer" },
        { id: "c", label: "Speedometer" },
        { id: "d", label: "None of these" },
      ],
      correct: "a",
    },
    {
      questionId: "th-ex-5",
      prompt: "The symbol for Fahrenheit is…",
      options: [
        { id: "a", label: "°C" },
        { id: "b", label: "°F" },
        { id: "c", label: "I" },
        { id: "d", label: "K" },
      ],
      correct: "b",
    },
    {
      questionId: "th-ex-6",
      prompt: "A wooden spoon is dipped in a cup of ice cream. Its other end…",
      options: [
        { id: "a", label: "Becomes cold through conduction" },
        { id: "b", label: "Becomes cold through convection" },
        { id: "c", label: "Becomes cold through radiation" },
        { id: "d", label: "Does not become cold" },
      ],
      correct: "d",
      explain: "Wood is an insulator — heat (or cold) barely passes along it, so the far end stays unaffected.",
    },
    {
      questionId: "th-ex-7",
      prompt: "The device used for measuring temperature is called a…",
      options: [
        { id: "a", label: "Tachometer" },
        { id: "b", label: "Odometer" },
        { id: "c", label: "Thermometer" },
        { id: "d", label: "Barometer" },
      ],
      correct: "c",
    },
    {
      questionId: "th-ex-8",
      prompt: "The normal temperature of a healthy person is thirty-seven degrees on the…",
      options: [
        { id: "a", label: "Kelvin scale" },
        { id: "b", label: "Roemer scale" },
        { id: "c", label: "Fahrenheit scale" },
        { id: "d", label: "Celsius scale" },
      ],
      correct: "d",
    },
    {
      questionId: "th-ex-9",
      prompt: "Which of the following is NOT an insulator?",
      options: [
        { id: "a", label: "Brick" },
        { id: "b", label: "Bamboo" },
        { id: "c", label: "Brass" },
        { id: "d", label: "Cardboard" },
      ],
      correct: "c",
    },
    {
      questionId: "th-ex-10",
      prompt: "Woollen clothes keep us warm during winter because…",
      options: [
        { id: "a", label: "Wool is an insulator only" },
        { id: "b", label: "Wool is a conductor" },
        { id: "c", label: "Wool traps air (which is a poor conductor)" },
        { id: "d", label: "Wool has a vacuum inside" },
      ],
      correct: "c",
    },
    {
      questionId: "th-ex-11",
      prompt: "The heat from the Sun reaches us on the Earth through the process of…",
      options: [
        { id: "a", label: "Conduction" },
        { id: "b", label: "Convection" },
        { id: "c", label: "Radiation" },
        { id: "d", label: "None of these" },
      ],
      correct: "c",
    },
    {
      questionId: "th-ex-12",
      prompt: "Mercury boils at 357°C and melts at…",
      options: [
        { id: "a", label: "−38°C" },
        { id: "b", label: "0°C" },
        { id: "c", label: "100°C" },
        { id: "d", label: "−115°C" },
      ],
      correct: "a",
      explain: "Mercury freezes/melts at about −38°C — that's why alcohol is used for colder measurements.",
    },
    {
      questionId: "th-ex-13",
      prompt: "0°C is also called the ___ of a temperature scale.",
      options: [
        { id: "a", label: "Upper fixed point" },
        { id: "b", label: "Lower fixed point" },
        { id: "c", label: "Middle point" },
        { id: "d", label: "Boiling point" },
      ],
      correct: "b",
      explain: "0°C is the freezing point of water — the lower fixed point. 100°C is the upper fixed point.",
    },
    {
      questionId: "th-ex-14",
      prompt: "Heat is a form of energy that flows from a body at a ___ temperature to a body at a ___ temperature.",
      options: [
        { id: "a", label: "Higher … lower" },
        { id: "b", label: "Lower … higher" },
        { id: "c", label: "Equal … equal" },
        { id: "d", label: "Zero … high" },
      ],
      correct: "a",
    },
    {
      questionId: "th-ex-15",
      prompt: "Assertion: The thermometer that measures body temperature is called a clinical thermometer. Reason: The clinical thermometer is a short, broad and uniform glass tube.",
      options: [
        { id: "a", label: "Both A and R true, R explains A" },
        { id: "b", label: "Both A and R true, R does not explain A" },
        { id: "c", label: "A is true, R is false" },
        { id: "d", label: "A is false, R is true" },
      ],
      correct: "c",
      explain: "A is true, but a clinical thermometer is a LONG, NARROW tube (not short/broad), so R is false.",
    },
    // ——— True / False ———
    {
      questionId: "th-tf-1",
      prompt: "True or False: Heat flows from a hotter body to a colder body.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    {
      questionId: "th-tf-2",
      prompt: "True or False: The Sun's heat reaches the Earth by conduction.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "b",
      explain: "It reaches us by radiation — the only method that needs no medium.",
    },
    {
      questionId: "th-tf-3",
      prompt: "True or False: Wool is a good conductor of heat.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "b",
      explain: "Wool traps air, a poor conductor, so it keeps body heat in — it's an insulator.",
    },
    {
      questionId: "th-tf-4",
      prompt: "True or False: Dark-coloured clothes absorb more heat than light-coloured clothes.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    {
      questionId: "th-tf-5",
      prompt: "True or False: On the Celsius scale, water freezes at 0°C.",
      qtype: "true-false",
      options: [{ id: "a", label: "True" }, { id: "b", label: "False" }],
      correct: "a",
    },
    // ——— Fill in the blanks ———
    {
      questionId: "th-fb-1",
      prompt: "The instrument used to measure temperature is called a ______.",
      qtype: "fill-blank",
      answers: ["thermometer"],
    },
    {
      questionId: "th-fb-2",
      prompt: "The transfer of heat through a solid, particle to particle, is called ______.",
      qtype: "fill-blank",
      answers: ["conduction"],
    },
    {
      questionId: "th-fb-3",
      prompt: "The transfer of heat as waves, needing no medium, is called ______.",
      qtype: "fill-blank",
      answers: ["radiation"],
    },
    {
      questionId: "th-fb-4",
      prompt: "On the Celsius scale, water boils at ______ degrees.",
      qtype: "fill-blank",
      answers: ["100", "100°c", "100 c"],
    },
    {
      questionId: "th-fb-5",
      prompt: "The normal temperature of a healthy human body is ______ °C.",
      qtype: "fill-blank",
      answers: ["37"],
    },
  ],
};
